### ISSUE TITLE
Why _renderChildren is internal method (at least CompositeView)?

### ISSUE THREAD

**Issue by darky** [marionettejs/backbone.marionette#1302]
I want to render only itemViewContainer, but not all view.
_renderChildren very useful here, but it internal method and undesirable to use.

**Comment by GermainBergeron** [comment]
I'm not sure to understand why `_renderChildren` shouldn't be public.

In our web application we use a table view that can be filtered, sorted, paginated, etc. Basically the same functionality offered by [Datatables](http://www.datatables.net/). You can see an example [here](http://screencast.com/t/mXc1xkh8D) 

If we use a `CompositeView` with a table inside, we can specify the `ItemViews` to be rows in the table body. This allows us to do simple logic in the `addChild` function to determine if we render a row based on it's model.

Without the `renderChildren` function, the focus must be reinstated in the filter box, at the location of the cursor before the re-render, each time a user type a letter, the classes must be re-applied for the sort, the number of entries re-selected, etc. Because the entire view is re-rendered.

I'm not sure that triggering a reset of the collection is the most intuitive way to render the children, and only them.
