### ISSUE TITLE
Regions hash in LayoutView attaches regions that are outside the LayoutView's DOM tree

### ISSUE THREAD

**Issue by jmca** [marionettejs/backbone.marionette#1685]
The regions hash in LayoutView attaches regions that are outside of the LayoutView's DOM tree.

The expected behavior is that it should only grab the inner/scoped regions under the LayoutView DOM tree.

The example below is using `el: ...`, I have not tried this using an actual template. I'm using `_.template('')` only to thwart the "no template" exception.

```
<!DOCTYPE html>
<html>
<head>
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <script src="http://jashkenas.github.io/underscore/underscore-min.js"></script>
    <script src="http://jashkenas.github.io/backbone/backbone-min.js"></script>
    <script src="http://marionettejs.com/downloads/backbone.marionette.js"></script>
</head>

<body>
    <div class="some-region"></div>
    <div class="some-view">
        <div class="some-layout-view">
        <div class="some-region">A</div>
    </div>

    <script type="text/javascript">
        var SomeLayoutView = Marionette.LayoutView.extend({
            el: '.some-view',
            template: _.template(''),
            regions: {
                someRegion: '.some-region'
            }
        });

        var someLayoutView = new SomeLayoutView();
        someLayoutView.render();

        console.log('someLayout should have 1 region');
        console.log('Actual result: ' + someLayoutView.someRegion.$el.length);
                //Returns a length of 2
    </script>       
</body>
</html> 
```

**Comment by fabien** [comment]
@jmeas it appears that in the end it's still not possible to have scoping unless `el` is already defined (e.g. the view has been rendered). Am I missing something?

**Comment by jmeas** [comment]
@fabien what do you mean? Can you provide more info?

**Comment by fabien** [comment]
Well, unless the LayoutView has already been rendered, the `parentEl` that is passed in here will be `undefined` - which is always the case for template based layouts:

https://github.com/marionettejs/backbone.marionette/blob/master/src/layout-view.js#L107

However, if I take out this `this._isFirstRender` clause, and let `this._reinitializeRegions` run, it will work fine, and the region selector will be scoped to the LayoutView:

https://github.com/marionettejs/backbone.marionette/blob/master/src/layout-view.js#L39

**Comment by jmeas** [comment]
Make a new issue? //cc @megawac

**Comment by fabien** [comment]
@jmeas I don't have the time right now, sorry. 

My current workaround to have the regions correctly scoped and available when I need them:

```
initialize: function(options) {
    this.once('render', this.setupRegions);
},

setupRegions: function() {
    this.addRegion('container', {
        selector: '[data-region="container"]',
        regionClass: ContainerRegion
    });
    this.addRegion('details', '[data-region="details"]');
}
```

**Comment by sllanes** [comment]
I ran into the same issue as @fabien. It seems the ``parentEl`` is not set if using a ``LayoutView`` with a template because ``this.el`` is not yet initialized. I was able to workaround the issue by overriding the ``LayoutView`` constructor and moving the call to ``_initializeRegions`` after the call to the ``Marionette.ItemView`` constructor. This allows ``this.el`` to be initialized now that ``Backbone.View._ensureElement`` is called first. Changing the order does not appear to break anything in our project but I did notice the comment in the source that states ``// Ensure the regions are available when the 'initialize' method is called`` so my change would break that expectation. I have not had a need to use regions in my initialize method and just mostly in the "before:show" or "render" view events so as of now I am okay with the change. I would be interested in any thoughts or other suggestions.
