### ISSUE TITLE
UI elements should be rebound on setElement

### ISSUE THREAD

**Issue by pimlottc** [marionettejs/backbone.marionette#1952]
When re-binding the view to a new element via `setElement`, the `ui` elements should be updated within the context of the target element.  You can do this manually by calling `bindUIElements` but IMHO this should happen automatically.

Related to #1940.

Test case: http://jsfiddle.net/pimlottc/xvcv8fcw/13/
Clicking anywhere within the PeopleView will toggle the colors on the header, but when the view is reset to a different element (when you hit the Dupe button), `ui.title` still refers to the original header.

**Comment by jasonLaster** [comment]
I'd like to see this issue closed for the time being. I don't see us changing backbone.view behavior currently... If we start doing that, we can revisist these suggestions.

**Comment by paulfalgout** [comment]
I'm not certain that this is changing `backbone.view` behavior anymore than we already are.  Currently `setElement` in backbone calls `delegateEvents`.. so when you `setElement` on a Marionette.View you do get your `events` and `triggers` setup, but since the ui hash is not rebound the ui is still the old jQuery look ups.

I don't know if this affects whether the triggers works or not if they include `@ui.`  I _think_ they'd be fine.. 

So in order to fix this we'd have to add to the currently overridden `_setElement` or perhaps `delegateEvents` something to the effect of:

```js
if(this._isRendered){
  this. bindUIElements();
}
```

Essentially anytime `delegateEvents` needs to be recalled, you also need `bindUIElements` or your `Mn.View` breaks.

**Comment by jasonLaster** [comment]
Hmm persuaded me.

**Comment by ianmstew** [comment]
How would this break apps?  I'd like to get this into `2.5` if possible.

**Comment by JSteunou** [comment]
+1

**Comment by eth0lo** [comment]
Also when calling ``setElement`` on a ``CollectionView`` does not rebound the event handlers on the ``childViews``

Example: If you have a already rendered CollectionView (for example it was rendered server side) and want to rebound using ``setElement`` the delegateEvents are not propagated to the childViews, nor the childViews are set within the collectionView. The events that are bound are those that are defined inside the collectionView only

**Comment by paulfalgout** [comment]
https://github.com/marionettejs/backbone.marionette/blob/master/src/view.js#L100
