### ISSUE TITLE
Introduce `getUi`

### ISSUE THREAD

**Issue by jmeas** [marionettejs/backbone.marionette#2102]
View's `ui` hash stands out among the properties that Marionette introduces, and not in a good way. Unlike most (all?) other attributes, we modify the `ui` hash *directly* once the view has been rendered. Consequently, if you access `view.ui.myElement` before rendering, you get a string, and after rendering you get a jQuery object.

It would be much better, I think, if we left `this.ui` alone. It would *always* be strings. To access the ui elements, we would introduce a new API method: `getUi`.

```js
view.getUi('myElement');
```

If you call this before the view has been rendered, we throw a Marionette Error telling you to render it first. And if you call it after the view has been rendered, you get your jQuery object.

While we can't change `this.ui.x` until the next major release, we can introduce this new API method and encourage using it over the old means of accessing ui.

Thoughts?

**Comment by samccone** [comment]
it is in minor!

:dancer:  thanks again @duncanbeevers sorry about the delay

**Comment by JSteunou** [comment]
Noooooooooo 

Dont leave `ui` alone :(

**Comment by bazineta** [comment]
While this has been committed and thus I assume it's a done deal, this is a regression in my opinion.  You've gone from a situation where any modern editor will tell you that you've got a typo, to a situation where that can't happen, all apparently to address doing DOM manipulation after a view has been destroyed.

It that's indeed the case, then you've substituted, for an error path that's somewhat unlikely, one that's practically guaranteed.  I honestly can't see why literal strings sprinkled everywhere is somehow an improvement.

If you absolutely must go this route, then I would suggest an unadorned 'get' method that takes two parameters, the first being the thing to get, rather than innumerable getXXX methods.  If it's going to be literal strings anyway, then you may as well go for the gusto.

However, I think they're a constant source of errors, and I just can't see the logic here.

**Comment by samccone** [comment]
@JSteunou @bazineta please take a look at the implementation details

https://github.com/marionettejs/backbone.marionette/pull/2399/files

I think you will find that you can still use `UI` ... The motivation behind the abstraction is that it is a stable safe interface that throws an error in the case where your view is no more. 

You can still use ui directly. 


> I honestly can't see why literal strings sprinkled everywhere is somehow an improvement

Again this is just an interface you an choose to not use it, how do you feel about `getRegion('bar')`? and 
`showChildView('foo', ...)`

All just interfaces to make your life easier, but with the abstractions does come complexity, I appreciate your thoughts and feedback

**Comment by bazineta** [comment]
@samccone, when it's removed from the documentation, the message is not 'You can still use ui directly'.  Rather, it's 'You can no longer do this; stop now.'

**Comment by thejameskyle** [comment]
This was done for all the wrong reasons and should be reverted.

**Comment by JSteunou** [comment]
agreed with @bazineta on the fact that removing it from documentation can be interpreted as a deprecation and not to be used.
