### ISSUE TITLE
Rename `templateHelpers`

### ISSUE THREAD

**Issue by jmeas** [marionettejs/backbone.marionette#2166]
Marionette's views provide a fancy method called `templateHelpers.` This method provides a hook for you to add extra data to your template before it is rendered, which is super useful. But the name is terrible!

Firstly, there's no notion of helpers in Underscore templates, only `data`. In this case, `templateHelpers` are adding extra *data* to your template. In Handlebars lingo, this would be equivalent to adding to the `context` that you pass to your template. In neither situation, though, is this method dealing with anything called a 'helper.'

In fact, in Underscore there's no notion of helpers at all, so it's simply an invented term. And with Handlebars the situation is far worse – the method conflicts with Handlebars helpers, which are an *entirely different concept altogether*!

In my opinion, this method's name should reflect the fact that it is adding data, or context, to a template, and should not use the word 'helpers' at all.

Just to throw a possibility out there, `templateData` is one option. I can't say I'm super thrilled about this option, but I do think that it's better than `templateHelpers`.

**Comment by jasonLaster** [comment]
@thejameskyle coming back to the rename ticket. I think super should be its own discussion as it affects lots of hooks. 

How does renderData sound?

**Comment by jmeas** [comment]
Hmmm...do you think there's a chance for confusion with that name? A noun following a verb makes me think the verb is acting on that noun, so my initial read of that is 'we're rendering the data.' This is further made worse by our `renderTemplate` method. Calling it 'data for the template,' or `templateData`, seems slightly clearer to me than 'data used when rendering the template,' or `renderData`.

Even so...neither of these are right! This is simply additional data being added to the data for the template, so it shouldn't be called either of these things. I can't think up a better name at the moment, though :(

**Comment by ahumphreys87** [comment]
Gonna leave a few suggestions for discussion: 

`additionalData`
`templateProperties`
`templateAttributes`
`additionalAttributes`

Im leaning towards `attributes` as the noun - its consistent with how Backbone names the properties on a model. More thoughts @marionettejs/marionette-core ?

**Comment by jasonLaster** [comment]
hmm, I'd vote on `templateData` as attributes suggest model attributes and has more semantic meaning. As for `additional` that's 10 more chars that I'd rather avoid... If people like additional or something like that because we're collecting data from other sources as well, that'd be cool with me too though

**Comment by ianmstew** [comment]
`attributes` hash is serialized into the el's outerHTML, but `templateData` is the best so far IMO.  I wish I was more satisfied with it, though.

**Comment by ianmstew** [comment]
Oh, duh. `templateAttributes`.  `templateAttrs`?

**Comment by ahumphreys87** [comment]
I'd be up for templateAttrs

**Comment by ahumphreys87** [comment]
What about templateOptions? Is that a thing already?

**Comment by ianmstew** [comment]
I like "attrs" because the idea is to augment `model.attributes` with another, generally-flat structure.  I guess I see attributes as data ready for template serialization.  I have moved away from the term "data" in my personal use for all but the most generic cases, such as raw JSON response from an ajax request, because it can mean anything.

**Comment by ianmstew** [comment]
Hmm, templateOptions, as if it's basically the second parameter to the template engine besides the template itself?  Interesting!

**Comment by ahumphreys87** [comment]
Yeah my thoughts as well. templateAttributes is my favourite but if we
worried about the length then templateAttrs is good for me

I thought of templateOptions as we use options in views, but for
consistency we should go with attrs I think.

@jasonLaster @paulfalgout thoughts?

**Comment by jasonLaster** [comment]
Hmm, not convinced on the use of attributes or options. My problem with attributes is that they're being handled by serializeData, not templateHelpers. Options reminds me of view options which is kinda different. 

I guess I have a simplified model in my head, `function x packages data for the template`... and in code

```js
{
  templateData: function() {
     return {
        puppies: ['corgies', 'pugs'],
     }
  },

  render: function() {
     var data = _.extend(this.serializeData(), this.templateData());
     var html = template(data);
  }
}
```

**Comment by ianmstew** [comment]
I see your point on the parallel nature of serializeData and templateData.  I'm not opposed to templateData.

**Comment by paulfalgout** [comment]
`templateData` seems like the least bad possible name :ok:

**Comment by rhubarbselleven** [comment]
but it's not The Template Data.. It's working with it, expanding or manipulating it

**Comment by paulfalgout** [comment]
`presentData`  `presentationData` ...  
`transformData`
`manipulateData` 

naming things is the worst.

**Comment by jdaudier** [comment]
How about `extraData` or `addExtraData`? :smiley:

**Comment by rhubarbselleven** [comment]
http://marionettejs.com/docs/v2.4.1/marionette.view.html#viewtemplatehelpers

> A templateHelpers attribute can be applied to any View object that
renders a template. When this attribute is present its contents
will be mixed in to the data object that comes back from the
serializeData method. This will allow you to create helper methods
that can be called from within your templates. This is also a good place
to add data not returned from serializeData, such as calculated values.

Also, remember there's multiple definitions that can be in there. So the attribute needs to be pluralised

`templateCallbacks`
`templateDataCallbacks` ?

.. 

`templateHelpers` ?

**Comment by jasonLaster** [comment]
ooh, i like `presentData` and `prepareData`

@rhubarbselleven my take on this is that data can contain callbacks, but that's not the primary purpose. So maybe something that documentation touches on

**Comment by jridgewell** [comment]
I'm going to push back against this argument @jasonLaster v @thejameskyle argument: I think @thejameskyle has the right idea here, even without `super` support.

> I think we should discourage overriding serializeData it is inconsistent.

**Comment by jridgewell** [comment]
I'm going to push back against this argument @jasonLaster v @thejameskyle argument: I think @thejameskyle has the right idea here, even without `super` support.

> I think we should discourage overriding serializeData it is inconsistent.
> More generally we prefer before/after hooks over subclass overrides

I see this a needlessly complex, given we're combining data. Which data takes precedence? Where should I put extra data needed (someone's going to override `#serializeData`, it's public)? Providing a single point to override makes this much easier.

We've already [removed the complex logic](https://github.com/marionettejs/backbone.marionette/pull/2181/files#diff-3af187c4992bdc09baf44049e31c3d89R17) from `#serializeData`. If you need custom data, override it and mix in model data with `#serializeModel`. Or, with `#serializeCollection`. Either way, the code base is simpler because of it.

As for the `super` debate, I've _very_ rarely needed to override a sub-class' serializer. And calling super the old fashioned way isn't that hard when you do.

**Comment by paulfalgout** [comment]
What I tend to like about `templateHelpers` is that it's more configuration-like..  this isn't necessarily a reason to keep it, but I at one point refactored all of my `serializeData` to be `templateHelpers` and it helped clean it up.

I might have something like:
```js
templateHelpers: {
  date_display: function(){
    return _.moment(this.date).format();
  },
  issue: require('helpers').issue
}
```

would be
```js
serializeData: function(){
  var data = this.serializeModel(this.model);

  data.date_display = _.moment(this.model.get('date')).format();

  data.issue = require('helpers').issue.call(data);

  return data;
}
```

to some degree I'd rather make serializeData private.

**Comment by bazineta** [comment]
The reluctance to override serializeData seems a bit odd to me; frankly, it seems like by far the simplest approach.  TBH, we do this more often than not in our own codebase just to avoid serialization that we don't need.

**Comment by fcbajao** [comment]
The way I understand `templateHelpers`, they are used to help you decorate or present your data. So what about `dataDecorators` or `dataPresenters`? Does `data` have to be the last word?

**Comment by thejameskyle** [comment]
What I've learned while working on my current app is that inserting too many hooks becomes an anti-pattern over using super.

Backbone has the pattern of using `_.result`-like behavior for everything. The entire Backbone community uses it all over the place to allow people to specify configuration, and what this leads to is very unusual bugs while subclassing (See: https://github.com/jashkenas/backbone/issues/3408).

---

Marionette has two patterns that makes it even worse to deal with:

**First**, it will allow even more data structures for configuration in places. The worst example of this is Modules where you can specify them in any form you could dream up. Something that we all agreed was a terrible idea. However, there are lesser cases that still cause lots of weird issues and add complexity to subclassing (See: https://github.com/marionettejs/backbone.marionette/pull/2368#issuecomment-78166820).

**Second**, Marionette has more hooks than it should. I'll use `serializeData/templateHelpers` as an example since this is the topic of this issue. 

When you have `super`, everything works nicely. You have before and after hooks, you can extend the data to add more, even manipulate arguments easily, and generally everything works very naturally:

```js
serializeData(arg1 = {}, ...args) {
  before();
  extend(super.serializeData(arg1, ...args), {
    additionalData: {}
  });
  after();
}
```

However, if Marionette added all of these hooks you instead look something like this:

> Note: This might seem ridiculous with `serializeData` but these are patterns you can see all over Marionette.

```js
class View {
  initialize() {
    this.on('before:serializeData', () => {
      before();
    });
  }

  afterSerializeData() {
    after();
  }

  serializeData(arg1 = {}, ...args) {
    return super.serializeData(arg1, ...args);
  }

  templateHelpers(...args) {
    var sup = super.templateHelpers;
    var res = isFunction(sup) ? sup(...args) : sup; // templateHelpers could be specified multiple ways
    return extend(sup, {
      additionalData: {}
    });
  }
}
```

While this is a bit of an exaggerated case, you should be able to see how after a few hundred classes or so you start feeling death by a thousand paper cuts. You might ask why if I was already overriding `serializeData` I didn't just do everything inline....... exactly.

---

I used to be under the impression that adding all of these hooks is what made Marionette incredibly customizable and easy to use, but really at most they are micro-optimizations for small cases which end up causing headache after headache down the road.

The rules I've learned are:
- Specify _everything_ as a function (you don't want to deal with non-functions mixed with functions when calling super)
- Never use `triggerMethod` methods (they are just a level of misdirection and will frustrate you after a while)
- Always prefer `super` (don't use any extra hooks like `templateHelpers`, this is also true for `render`)

If you do these things, then the object model in Marionette will hurt a little bit less once your app grows.

It would be nice if Marionette learned to do this at a framework level, but people do love their hooks.

**Comment by jasonLaster** [comment]
@thejameskyle nice writeup. I generally agree that `super` is a powerful language feature that does help with several cases, but probably not all... in the abstract here's what I mean:

```js
function codeYay() {
   this.funcBeforeHook()
   // stuff
   this.fooBeforehook()
   // stuff
   this.fooAfterHook()
   //
   this.funcAfterHook()
}
```

In this example, the func hooks could be replaced with a well placed super call. Further more, the foo hooks could be replaced if foo were refactored to be it's own function.

So, why do we use hooks at all? What's the value? Two reasons:
1. offer an option that's simpler... it's easy to document that the best way to add data to a template is with `templateHelpers`... this is simpler than saying user serialize data, call super, and merge data.
2. offer an option for customization... one common pattern with parent classes is that they handle common data and allow subclasses to customize. requiring developers to call super couples the subclass to the parent class in terms of implementation and creates a degree of brittlness. If the internals of serializeData change, then all of the super call sites could be affected. The alternative is to decouple via a hook and honor a contract that returned data from templateHelpers will be added to the template.


Does this meta discussion matter? Who knows, but it's fun right....

**Comment by bazineta** [comment]
I think the key advantage with the override is that serializeData() is solving a general problem, but the implementor is solving a specific one.  I'd much rather be able to just override than have to both deal with the general-case that serializeData() must perform, often in a manner that is ends up being comically inefficient, and have to also juggle a myriad of hooks, so that it's 'simpler'.

We're schlepping model and collection data into a format usable by a template here.  There's a point where it's already simple enough, IMO.

**Comment by jasonLaster** [comment]
Here's where my writeup came from fyi:

Sandi Matz wrote a great book on object oriented design
http://janeeats.github.io/blog/2013/04/29/notes-on-chapters-1-to-3-of-poodir/

in it, she describes the key benefits to hooks or the **Template Method Pattern**. Search for either term and you'll find it:

> Template Method Pattern - Template Method allows you to “define a basic structure in the superclass and send messages to acquire subclass-specific contributions.” “Hook methods allow subclasses to contribute specializations without knowing the abstract algorithm. They reduce coupling between layers of hierarchy and increase its tolerance for change.”

**Comment by jridgewell** [comment]
> in it, she describes the key benefits to hooks or the Template Method Pattern.

But `#serializeData` is already a hook...

> 2. offer an option for customization... one common pattern with parent classes is that they handle common data and allow subclasses to customize.

Adding another hook doesn't solve this. What happens when I want to override `#templateHelpers` in a subclass? We're in the same boat, and now we just have two hooks.

**Comment by jasonLaster** [comment]
Cap'n hook

Yea I'm talking abstract here. I don't feel strongly bout TH. We could kill it.

**Comment by paulfalgout** [comment]
Personally I like very shallow extends.  So there is rarely the case in which I'm going to create a view where I would ever need to call the super of either `serializeData` or `templateHelpers`.  That said, I find `templateHelpers` cleaner when doing very simple tasks.  I don't think I use `serializeData` at all anymore.

**Comment by ianmstew** [comment]
I don't see `serializeData` as a hook because it is not an "abstract method".  I.e., it has an [implementation in the prototype chain](https://github.com/marionettejs/backbone.marionette/blob/286349f73b0f6e80642c2beddd66bee3736f865a/src/item-view.js#L15-L39) that is necessary for templating to function.  Meanwhile, `templateHelpers` [is purely user defined](https://github.com/marionettejs/backbone.marionette/blob/286349f73b0f6e80642c2beddd66bee3736f865a/src/view.js#L48-L49), meeting my personal working definition of  a "hook".

If we agree that a hook is useful for the reasons Jason proposed, then I suggest we keep `templateHelpers`.  If a hook is not useful, then kill it.  I do find it easier to say "hey, templateHelpers" to a newbie than "hey, prototype-chain conscience method override".  Maybe that's just a JS thing, because in Java land overrides seem to be more common.

Oh, by the way, my final naming suggestion: `templateHelpers` => `moarDataPls`.

**Comment by thejameskyle** [comment]
> That being said, I do find it easier to say "hey, templateHelpers" to a newbie than "hey, prototype-chain conscious method override".

It's better to teach new users the simple patterns that they should be using all the time than have two things that they use at different times.

People will need to eventually learn how to use `super()`, better to do it sooner rather than later.

> I don't see serializeData as a hook because it is not an "abstract method".

In a class every public method can be overridden, they are all hooks. Even if they already do something, that's what `super()` is for.

Abstract methods only exist in a class when there is a potential use case when subclassed, but the class itself doesn't actually have a use case for it.

**Comment by ianmstew** [comment]
@thejameskyle I see your point.  The `super()` pattern is fundamental to OO, including Javascript, and something developers should learn sooner rather than later.  I also see how the definition of a "hook" can be argued to include a method with a superclass implementation.  Additionally, Backbone sets a precedent for data method overrides with Model `parse()` and `toJSON()`.  Considering all of that, I am not opposed to requiring a `super()` style override for data concerns.

I have one final question.  To this point, Marionette views do not necessitate `super()` calls.  It is entirely possible to write perfectly flat, super-agnostic views thanks to triggerMethod hooks like onRender and onAttach.  I personally love triggerMethod hooks for that reason.  Removing `templateHelpers` in favor of a `serializeData` means some views would no longer be super-agnostic.  Do we want to begin a new view pattern?

Here's how I would summarize the discussion: `templateHelpers` allows for data massaging while maintaining the Marionette pattern of super-agnostic views.  Overriding `serializeData` is more consistent with Backbone data handling, and for that reason more "logically pure".  The question is, which is more important?  There isn't a clear winner in my mind, so I have to land on the status quo until I reach more conviction.

**Comment by thejameskyle** [comment]
> It is entirely possible to write perfectly flat, super-agnostic views thanks to triggerMethod hooks like onRender and onAttach.

I have to disagree with this point today, unless you are only subclassing built-in views once you will constantly be calling super methods. To give you an example, almost all of our views end up looking like this:

```js
BaseView.extend({
  templateHelpers() {
    return extend(BaseView.prototype.templateHelpers.apply(this, arguments), {
      // ...
    });
  },
  regions() {
    return extend(BaseView.prototype.regions.apply(this, arguments), {
      // ...
    });
  },
  onRender() {
    BaseView.prototype.onRender.apply(this, arguments)
    // ...
  }
});
```

I just grep'd through our code base for uses of `/(call|apply)\(this,/` (which glancing through seems like almost entirely super calls) we have hundreds of uses (~250).

The painful part isn't that we use super calls though, those work really well. The problem is that Marionette is at times [hostile towards calling super](https://github.com/marionettejs/backbone.marionette/pull/2368#issuecomment-78166820). Adding more hooks does not solve this problem, it exacerbates it by forcing the consumer to know more about the parent class.

**Comment by ianmstew** [comment]
I see now.  I'm coming from a completely different viewpoint considering 1. I am in complete control of our view architecture, and 2. I go to lengths to never subclass a user view mainly because extending prototype objects is so painful, like you just illustrated.

I read over the linked issues and it sounds like a deeper philosophy of "to subclass or not to subclass".  I agree Marionette does not cater to user view subclassing.  Seeing how these discussions tend to die unresolved I would love to hash this out over a Hangout.  This could be a good time for it considering Metal with your simplified `super()` impl is moving into core.

@marionettejs/marionette-core, topic for Tue 5pm meeting?

**Comment by bazineta** [comment]
The one and only thing in the above discussion that concerns me greatly is the concept of making serializeData() private.  TBH, presuming that you know how to serialize my data and preventing me from doing so is something that I just can't get my head around; if I wanted to be dictated to, I'd have chosen one of the frameworks that does that.

**Comment by mateomurphy** [comment]
To reiterate @rhubarbselleven comment, the docs say `This will allow you to create helper methods
that can be called from within your templates.`. Does the desire to rename `templateHelpers` go with a belief that it shouldn't contain any methods?

**Comment by jmeas** [comment]
> the docs say This will allow you to create helper methods that can be called from within your templates.. Does the desire to rename templateHelpers go with a belief that it shouldn't contain any methods?

no

**Comment by mateomurphy** [comment]
Then I'd argue that if `templateHelpers` contains methods, it's more than just data being added to the data for the template? Perhaps "helper" isn't the best name, but something that just contains "data" doesn't really work, IMO.

**Comment by Tvrqvoise** [comment]
Proposing ```getContext``` as a name.  It's a verb, is agnostic to what you're passing in, and matches some template languages' nomenclature.  Either way, I totally agree that having both of these methods is overkill.

**Comment by howardroark** [comment]
I think `templateContext` sums it up for me.

**Comment by ianmstew** [comment]
I think `templateContext` is the best yet.  It implies that the context of methods within the hash are part of the template's context not the view's, which is the case.

**Comment by jmeas** [comment]
:+1: for `templateContext`

**Comment by howardroark** [comment]
In Django a very similar sort of pattern is referred to as template context, that is what brought it to mind.
