### ISSUE TITLE
Weird behavior of UI element on :visible selector

### ISSUE THREAD

**Issue by coderek** [marionettejs/backbone.marionette#2184]
Version 2.3.0

Please take a look of the example here
http://jsfiddle.net/coderek/zcr1x7dm/3/

```html
<div class="content"></div>

<div>
    <h4>Before show</h4>
    <label>UI count: </label><span class="count-before-show"></span><br/>
    <label>Real count: </label><span class="real-count-before-show"></span>
</div>

<div>
    <h4>After show</h4>
    <label>UI count: </label><span class="count-after-show"></span><br/>
    <label>Real count: </label><span class="real-count-after-show"></span>
</div>

<script type='scripts/template' id='template'>
    <div class="hide components">User profile</div>
    <div class="components">Dashboard</div>
</script>
```

``` javascript
    ui: {
        'components': '.components:visible'
    },

    onBeforeShow: function () {
        $('.count-before-show').text(this.ui.components.length); // 0
        $('.real-count-before-show').text(this.$('.components:visible').length); // 0
    },
    
    onShow: function () {
        $('.count-after-show').text(this.ui.components.length); // 0
        $('.real-count-after-show').text(this.$('.components:visible').length); // 1
    }
```

UI element with `:visible` in the selector produce different outcome from the vanilla jQuery selector. 
I suppose this is a bug.

**Comment by jfairbank** [comment]
Hi, @coderek. At first glance, I believe this is currently expected behavior.

What happens when the view is shown is it gets rendered before it's actually added to the DOM tree. When it's rendered is when the UI elements are bound. However, because `.components` aren't yet attached to the DOM tree, then `.components:visible` will be empty.

By the time `onShow` is called and it is in the DOM tree, the UI elements were already bound, so they'll still be empty.

You could modify `onShow` to rebind UI elements and then get access:

```js
onShow: function() {
  this.unbindUIElements();
  this.bindUIElements();
  $('.count-after-show').text(this.ui.components.length); // 1
  $('.real-count-after-show').text(this.$('.components:visible').length); // 1
}
```

Does that help?

**Comment by jmeas** [comment]
@jfairbank's analysis is accurate. For 'dynamically-created views' – which is to say, views that create a wrapping element and then render a template inside of that created element – the `ui` will be bound **before** the element is a child of the `document`. As such, using the `:visible` pseudoselector doesn't work.

In general, `ui` doesn't work well for dynamic UI elements because they are never updated after the initial render. They're bound once and effectively forgotten about. You would need to create your own abstraction to keep it up-to-date. The simplest one would be doing what @jfairbank recommended, where you just update it a single time `onShow`. The name `components` suggests to me that these things might be created and destroyed throughout your view's lifecycle, though.

If that is accurate, what I might do is make a `ui` element that is the **container** of the components. Then, later, you could do `this.ui.components.children().filter(':visible')` or w.e. (that's pseudocode & may not work).

**Comment by coderek** [comment]
Technically, it makes sense to me now. But this is kind of, making the UI binding less useful if not confusing.

What I would suggest is to make `ui` a function instead of an cache object. So we can use `this.ui('components')` to invoke the jQuery selector every time.

**Comment by samccone** [comment]
@coderek there is something like that .. `this.$('.foo:visible')`

right? :)

**Comment by coderek** [comment]
@samccone 

But that defeats the purpose of having a `ui` hash right? (Sorry if I understand it in a wrong way)

**Comment by jfairbank** [comment]
@coderek Aside from providing more manageable string keys for interacting with child elements, the ui hash caches those elements as jQuery objects. If it were a function, it would defeat the purpose of caching if it invoked the DOM lookup every time. I understand your dilemma, but this implementation is at the mercy of jQuery when it comes to using `:visible` in your selector. I would suggest altering your selector to work off a class like `.visible` instead. So, you would hide `.components` by default and only display it if it also has the `.visible` class.

**Comment by reidcooper** [comment]
I just ran into this issue as well - I do understand the intended implementation and as to what @coderek was expecting (as am I), how can do the same thing but with a Marionette.Behavior? Does the UI hash operate the same as a View UI hash? In that case, do I have to rebind the UI elements in the View or do I have to do that in the Behavior?

**Comment by paulfalgout** [comment]
A behavior can access the view directly so `this.view.$('.foo:visible')` I think
