### ISSUE TITLE
LayoutView automatically loads views in defined regions

### ISSUE THREAD

**Issue by nanuclickity** [marionettejs/backbone.marionette#2192]
Why ?
--------
Layouts have multiple regions and for most of it's use cases, a view needs to be added to it's regions as soon as layout is initialized.

What ?
---------
We already have a key named regions. I propose another key regionViews.
 e.g.
 ``` javascript
regions:
  Header : '.app-header'
  Content: '.app-content'

regionViews:
  Header : 'modules/header/view'
  Content: 'modules/stats/view'
```

How ?
--------
We can load and append views after layout's `'render'` event.
This is a requirejs based problem, but can be extended to use of global objects, and hence supporting modules too.

```javascript
regionViews:
  Header : 'modules/header/view'
  Content: 'App.ViewDefs.StatsView'
```

When a layout is rendered.
We build a `new view()` from values given in regionViews, and append it to corresponding regions.

Additional
-------------
This will be backwards compatible. Initializers will check for existence of regionViews key.
I know that support for script loaders such as requirejs might not get introduced.
But, let me know.

**Comment by samccone** [comment]
Hey @nanuclickity thanks for the great writeup

I have implemented a behavior that does just this

https://github.com/samccone/marionette-behaviors#autoregion
https://github.com/samccone/marionette-behaviors/blob/master/auto_region.coffee

For now I think we are going to keep this idea out of core since adding a view to a new region can be simple (as your example points out) however it can also be quite complex, such when you want to fetch something async, attach it to a view instance and THEN render it into the region.

Let me know if you have any other thoughts, but behaviors were built to allow you to take care of this kind of "Refactor / Optimization" within your own application, depending on your specific needs.

Again thanks for the great issue.

**Comment by jmeas** [comment]
@nanuclickity, I haven't told anyone else about this, but my long-term vision is that this could be the default behavior for LayoutViews. It's by far the most common use case, and gives us more power in serializing and working wih the view tree, which is more necessary for a more opinionated router. i haven't fully worked out the details, but I envision that using the 'manual API' would only be used if you wanted to animate an old view out, and bring a new one in.

**Comment by samccone** [comment]
That is a fair idea @jmeas.

I would love to see an issue exploring the possible API to handle this use case.
The reason this has not been implemented in the core of the lib is because currently we do not take care of these types of auto linking for people automatically. 

As we have laid out in the direction for V3 this mind set is changing which will open the door for these kinds of improvements to reduce boiler plate and improve overall developer experience.

**Comment by jmeas** [comment]
:+1:

**Comment by nanuclickity** [comment]
Well, a module can have only two statuses - loaded or not loaded.

regionViews:

**Comment by nanuclickity** [comment]
How about something like this?

```coffeescript
# As a global
Marionette.scriptLoader = 'requirejs'

# In our layouts
regionViews:
  Header:  'modules/header/layout'
  Content: 'App.ViewDefs.Listview'
```

@jmeas is right, marionette is all about automating the boilerplate work, and it's hard to think that marionette wouldn't support async loaders. ( :smiley:  excited for v3 )

It'll be just checks for existence of keys provided in regionViews.
If no match is found, we resort to Marionette.scriptLoader. 

I'm working on a proof of concept for this.
Will push soon.

**Comment by nanuclickity** [comment]
or we could just check existence of a '.' or '/' in values. :P
