### ISSUE TITLE
App Sub Applications

### ISSUE THREAD

**Issue by samccone** [marionettejs/backbone.marionette#2201]
Application objects should be able to have "sub" applications that are started and destroyed on parent app state change.

```js
Mn.Application.extend({
  applications: {
    "myApp1": {
      class: MyApp1
      options: {}
    },
    "myApp2": MyApp2,
    "myApp3": {
      getClass: function(){},
      getOptions: {}
    }
  }
})
```

Each application has a name to make it simple to interact with it from within the parent app.

Related #2200

**Comment by paulfalgout** [comment]
Also related https://github.com/marionettejs/backbone.marionette/issues/2026

**Comment by jasonLaster** [comment]
Ooh pretty

**Comment by JSteunou** [comment]
I can live with a removal of Mn.Module with this sub app feature :)

**Comment by rafde** [comment]
Modules gone.

**Comment by paulfalgout** [comment]
While I dunno that this needs to be a part of Mn, I dunno how it related to modules?

**Comment by rafde** [comment]
I thought you needed Modules to have SubApps

**Comment by paulfalgout** [comment]
I think this is suggesting using Applications or some new object as sub apps.  unrelated to modules... kind of like https://github.com/marionettejs/backbone.marionette/issues/2026 which suggests removing modules and adding subapps.  Either way I think it safe to close both of these for now.  Hopefully, for the moment at least, we can focus more on doing less better, rather than adding stuff.
