### ISSUE TITLE
Trigger onAttach on child views during CollectionView re-render

### ISSUE THREAD

**Issue by MeoMix** [marionettejs/backbone.marionette#2209]
The current implementation of onAttach does not trigger when an ItemView is attached to the DOM during re-rendering of a CollectionView. Although no region is being used I believe it makes sense to trigger onAttach in a fashion similar to how onShow is triggered.

**Comment by jmeas** [comment]
:+1: Makes sense to me.

My implementation of `onAttach` is *closely* linked to the `onShow` event. I (incorrectly) assumed that only regions trigger the `onShow` event. But Collection Views trigger it on their children, as well!

**Comment by bazineta** [comment]
Further to the discussion here, a rehash of Gitter discussion on this topic.

I have a view hierarchy LayoutView -> CollectionView -> LayoutView -> ItemView.  The final ItemView contains a div that hosts a Highcharts chart; for the chart to render properly, the width metric must be valid when the ItemView is shown.

To date, I've used onShow() in both LayoutViews to instantiate the CollectionView and ItemView, respectively, and onShow() in the ItemView to display the Highcharts chart.  This works correctly, and the width in the ItemView is valid in its onShow().

Attempting to use the new onAttach() function to perform the same function works, sort of.  If the chart is displayed in onAttach() and the LayoutViews instantiate their children in onRender() instead of onShow(),  the ItemView ends up with a valid width in onAttach() on first render.  Using this setup, it's got an invalid width in onShow().

However, if the collection is reset, onAttach() won't be called, so the effect is that the ItemViews are destroyed and recreated, but the charts don't get drawn, as onAttach() is never called.

**Comment by musterknabe** [comment]
:+1:  Bumped into this aswell

**Comment by jasonLaster** [comment]
Thanks for the bump @musterknabe. @ianmstew want to become our collection view events :older_man:? Half joking, no pressure

**Comment by ianmstew** [comment]
Ahhh, I'll look into it... might as well while I'm down there :)

**Comment by ahumphreys87** [comment]
Fixed with #2481
