### ISSUE TITLE
LayoutView+CollectionView vs CompositeView

### ISSUE THREAD

**Issue by trusktr** [marionettejs/backbone.marionette#2239]
Is there any preference for one over the other in cases where you want an outer template around a single collection? For example, would you make a LayoutView that has a `<thead>` and `<tbody>` a body, then put a CollectionView of rows into it's single region, or would you use a CompositeView with itemView set for the rows?

They seem intrinsically the same.  Which method is more advantageous, and what is it's most significant advantage?

**Comment by Tvrqvoise** [comment]
I guess the answer is that with CompositeView you only have to write the one view, whereas with LayoutView + CollectionView you have to write an extra view, but get regions out of the deal (if for example you wanted to put another view in the <THEAD>).  Which does make me wonder why composite view extends from ItemView instead of LayoutView.  Does it cause memory issues?

**Comment by paulfalgout** [comment]
@trusktr welcome!  

I personally think that a `LayoutView` is safer in most instances.  If you find you have to re-render some part of the DOM wrapping the list, you'll be out of luck with the `CompositeView` unless you want to re-render the entire list as well.  With a `LayoutView` you can add a new region and render that part separate from the `CollectionView`  `CompositeViews` often seem like they're clever and saving some boilerplate, but I often find myself regretting using them in the long run.  But they're not entirely without merit.. just potentially not as useful as they may seem at first.

You should join us on [Gitter](https://gitter.im/marionettejs/backbone.marionette) if you haven't already.  It's great for discussions like these.

**Comment by samccone** [comment]
going to close as more of a general question and not really an issue.

as @paulfalgout said, please join us in gitter to talk about these topics.

**Comment by trusktr** [comment]
Thanks guys! I've settled with LayoutView. It seems more flexible/customizable. @betovelandia

**Comment by jmeas** [comment]
CompositeView only exists as a distinct view because Regions have a wrapping element. Once https://github.com/marionettejs/backbone.marionette/issues/1976 lands, we could get rid of all that unnecessary code. At that point, we could keep the same API around for CompositeView, or get rid of it and just suggest using LayoutView + CollectionView. These questions are part of the larger discussion around moving from 4 to 2 views.

That might sound drastic, but it shouldn't affect your decisions now. Because of the issue of the wrapping node, CompositeView offers a different set of functionality to LayoutView+CollectionView, so just use whatever the situation requires.
