### ISSUE TITLE
View.triggers do not return event arguments, and lack continueity with the rest of marionette

### ISSUE THREAD

**Issue by RealAdamSinger** [marionettejs/backbone.marionette#2343]
Problem: 
View.triggers returns the arguments view, model, collection (inconsistent with the rest of marionette, and poor practice)

Solutions:
return only the "event" object, keeping consistent with how view.events operates, and have the function scoped to the view's "this", similarly with the rest of marionette. there is no need to return model and collection, they are already properties of the view

i have solved this myself by overwriting Marionette.View.prototype._buildViewTrigger like so..
```js
Marionette.View.prototype._buildViewTrigger = function(triggerDef) {//triggers function over-ride
    return function(e) {
        this.triggerMethod(triggerDef.event, e);
    };
};
```

**Comment by jasonLaster** [comment]
hey @RealAdamSinger this point has been brought up before. You're not the first to suggest this

https://github.com/marionettejs/backbone.marionette/issues/1329
https://github.com/marionettejs/backbone.marionette/pull/441

I'd consider this pattern in a nutshell a map between DOM and VIEW events.that's why e isn't there, if you want to handle the event use events

**Comment by samccone** [comment]
Going to close because @derickbailey did a great job explaining why it is a bad idea / anti-pattern in #441 that I still agree with.

Thanks for raising the point @RealAdamSinger appreciate the critical thought

**Comment by jmeas** [comment]
Note for future visitors:

> i have solved this myself by overwriting Marionette.View.prototype._buildViewTrigger like so..

Do not do this ^
