### ISSUE TITLE
Fork Backbone

### ISSUE THREAD

**Issue by thejameskyle** [marionettejs/backbone.marionette#2349]
After the 1.8 release of underscore, I've finally been pushed over the edge. This is worth discussing.

https://github.com/jashkenas/underscore/issues/2061
https://github.com/jashkenas/underscore/issues/2062

**Comment by jmeas** [comment]
@thejameskyle, I think this might be a bit of a strong reaction. I mean, fork Backbone? Really? It's not worth maintaining that, is it? If you feel this strongly, you should go support the [Exoskeleton](https://github.com/paulmillr/exoskeleton) project. You'll be free from Underscore and jQuery.

When you think about it, this is just another minor release that breaks things. But that's okay, because we're used to it and have [guarded ourselves (and our users) against it](https://github.com/marionettejs/backbone.marionette/blob/master/package.json#L46).

I think things are good. No need for forks.

**Comment by recurrence** [comment]
Lodash also gets plenty of breaking changes. :)

**Comment by jdalton** [comment]
lodash follows semver so there's that ;)

**Comment by thejameskyle** [comment]
> Really? It's not worth maintaining that, is it?

@jmeas It would take me a few hours to write a script that syncs up the two projects at every commit.

> you should go support the Exoskeleton project. You'll be free from Underscore and jQuery.

I would support switching to this dependency as well.

> I think this might be a bit of a strong reaction.

This is not the first time I've brought it up, I've been saying we should do this for awhile and not only for lodash. Just the other day I was speaking to @jasonLaster about how the inheritance chain from Marionette.Class could be messed with if you import your files in a crazy order, and how a fork that included a base class could support this. There's also the issue where we can modify Backbone's extend to support ES6 classes.

All of this said I'll be starting an email thread with contributors to Underscore and Lodash on how we can improve the experience for users, even if that means deprecating Underscore in favor of Lodash.

**Comment by jmeas** [comment]
One of the big reasons that many people use Marionette is that you can just plop it on top of your Backbone app, and it works. I worry we may lose more than we would gain by making those changes.

**Comment by thejameskyle** [comment]
@jmeas If it's a compatible API then you should just be able to swap it out and get a better experience from end to end then simply plopping it on top. The same way (the vast majority of) apps can just swap out Underscore with Lodash today and have _everything_ improve.

**Comment by vinnymac** [comment]
@thejameskyle an important feature that people look for when using Underscore is the small footprint it has on their applications. I am for this change as long as we only use as much of LoDash as we need in the fork. If the fork requires the entire LoDash toolbelt it won't be as adoptable.

**Comment by jdalton** [comment]
fwiw yeoman's backbone generator [defaults to using lodash](https://github.com/yeoman/generator-backbone#options).

**Comment by thejameskyle** [comment]
@vinnymac The footprint isn't nearly as significant for most applications as one might think 5kb vs 15kb is nothing on most connections. If it really is an issue for you then let me offer you a [free CloudFlare account](https://www.cloudflare.com/plans) for all of your applications to be delivered on a globally distributed CDN. 

Also, lodash distributes every single method as its own file/module so you can require them as needed.

**Comment by jmeas** [comment]
@thejameskyle, make PRs and we can go from there.

> Fwiw Yeoman's Backbone generator defaults to using lodash.

Maybe even more compelling is that [BBB uses Lo-dash](https://github.com/backbone-boilerplate/backbone-boilerplate/blob/master/bower.json#L6)

**Comment by vinnymac** [comment]
@thejameskyle It was definitely a concern of mine, but 10 KB difference (gzipped?) is much smaller than I thought it would be. If it distributes as you require them then there is reason to use the more perform-ant tool over underscore. I would use this, however I would want the fork to strictly remain as a replacement to using Underscore without any other alterations to Backbone. (backbone.lodash = backlash?)

**Comment by thejameskyle** [comment]
omg omg omg omg backlash [isn't](https://www.npmjs.com/package/backlash) [taken](http://bower.io/search/?q=backlash).

It probably wouldn't be hard just to polyfill missing _ methods at the top if the _ object doesn't exist (for modules depending on globals). We can also just require in the exact methods we need if a module system is being used (cjs/amd/esm).

I still think forking backbone and replacing underscore with lodash would be the way to go though, it'd be simple to write a script that keeps it up to date.

**Comment by paulfalgout** [comment]
I realize this adds little value, but it's been a pretty ridiculous day already

https://twitter.com/otterball/status/568630186524213248

**Comment by jdalton** [comment]
You can use lodash with Backbone without forking using the Browserify transform [aliasify](https://www.npmjs.com/package/aliasify) or AMD "paths" config.

**Comment by thejameskyle** [comment]
@jdalton Yup, I do that on every project. However, since Backbone uses Underscore by default many users of Marionette are using Underscore today.

**Comment by jmeas** [comment]
> You can use lodash with Backbone without forking using the Browserify transform aliasify
> or the AMD "paths" config object.

Mhm, mhm – and I'm sure you're familiar with Webpack's similar feature. As much as I want to switch to LoDash *and* keep the Backbone dependency, I'd rather not require that people do extra shuffling in their build system to make it work. Setting $ on Backbone is already causing people enough trouble!

Though I suppose if we fork Backbone, then people would need to install our fork *instead* of Backbone, which could be just as (if not more) confusing to our users.

**Comment by jdalton** [comment]
> Mhm, mhm – and I'm sure you're familiar with Webpack's similar feature. 

I'm not can you point me in the right direction.

**Comment by jmeas** [comment]
:stuck_out_tongue:

**Comment by sentientnebula** [comment]
I'd be in favor of a fork that stays in sync with the original, and  whose only purpose is to substitute lodash for underscore.  I wouldn't want it to start diverging in any other ways where becomes incompatible with all the other nice add-ons available for backbone.

**Comment by samccone** [comment]
So to be clear you guys are thinking of forking backbone in a `lodash` style mentality.

Obviously I think a bunch of the BB contributors would welcome a OS lib that was friendly to contributors and was ran in an open fashion, thus pulling all of them in. 

I am not opposed to this, so long as we maintain 100% compatibility (even with a compatibility build like lodash). This fork would obviously need a person that wants to own it i.e @jdalton style. 

Thoughts? Concerns?

**Comment by jmeas** [comment]
I'm torn between thinking it's a crazy idea and a good one, but I would assist in maintaining it. At least until we see if it gets any traction from the community.

**Comment by ryanflorence** [comment]
> I'm not. Can you point me in the right direction.

```
{
  resolve: {
    alias: {
      'underscore': 'lodash'
    }
  }
}
```

**Comment by mattd** [comment]
> Thoughts? Concerns?

Yeah. I'm concerned. This sounds like you're adding complexity and confusion for very little gain.

Also, to echo the implicit concern raised by @sentientnebula: the very fact that the fork has happened may cause folks to start poking at the forked version of Backbone. Even opening up the possibility of deviating from Backbone's mainline sounds like a nightmare.

**Comment by stephanebachelier** [comment]
@thejameskyle why fork Backbone ? as others pointed before, breaking changes from minor can happen, but semver is a good way to avoid this kind of problem.

Backbone works really well with lodash since a long time. 

Just an idea, but if you are worried about es6 and Backbone.extend why not compose with Backbone instead of inheriting Backbone "classes" ?

**Comment by paulfalgout** [comment]
@stephanebachelier The concerns as I see it are that the library is ultimately controlled by one guy, who will and has undone the work of the community at the last moment and is willing to release quickly without testing.  Just check out the hundreds of lines of commits and rewrites and renaming that was done in the couple of hours prior to underscore `1.8.0`s release which immediately broke a bunch of tests. 

I can see risks on either side.  If there is a fork of backbone, it might fragment the community.. it might make things more complicated for people to get into.. it could shy people away because of the division in general.  However some might see it as needed stability.  Staying where we are is tying the future of whatever app you build to the actions of one single individual, who has shown he's ok wielding that power to his will.  And those kinds of actions may scare people away just as much as a stable fork might.  

Really Underscore/Backbone should be moved to a bigger organization, or it should be forked, otherwise we are completely at Jeremy's mercy.  I'd like to be able to trust him, but his track record lately is poor and unapologetic.

**Comment by framerate** [comment]
Can someone fill me in on why this is even an issue? I am and always have used underscore in production and haven't yet reached a reason to consider lodash. At first glance this issue seems like it's people are mad since some of the lesser used functions changed, people are demanding this be 2.0.0 to follow semver and threatening to stop using Underscore because of it?

Or is there more to this story? Fill me in, friends!

**Comment by paulfalgout** [comment]
@framerate essentially there's instability in these libraries.  Jeremy rushed the `1.8.0` release and it was not tested and was very broken in older browsers it is supposed to support.  Additionally the release was built quickly without any peers in a few hours, during which many things were reverted, rewritten, or renamed without any sort of conversation.  So there's an argument for a community run library that isn't entirely subject to the preferences of one person.  It's possible for libraries to be fine under one person, but in this case he's head of multiple large libraries, of which he has, self-proclaimed, little time to invest in.  This is evident in the very long release cycle and extremely rushed releases.  It's just not healthy.

**Comment by recurrence** [comment]
Interesting, didn't realize the situation was that bad.  Why did that happen?  I'm curious as I don't find projects without hard release schedules have such surge phenomena.

**Comment by stephanebachelier** [comment]
@paulfalgout Thanks for your explanations. It reminds me of the io fork from node. 
Marionette had this problem when Derrick was the only author. Not only one guy taking the decision might be bad but also it is slower to release.

Don't know what to think about a fork: It will consume time we need to develop our libraries or apps, but at the same time if Jeremy does not want a more collaborative approach it might be better to fork. Wait and see.

**Comment by blikblum** [comment]
The recent underscore release was really a disaster and hurts the confidence in it. On the other side  seems that there are no issues with Backbone itself. 
So, while i think reasonable to switch to lodash, is really necessary to fork Backbone?
BB Yeoman generator switched to lodash without the need to fork Backbone.

**Comment by Anachron** [comment]
Hey guys, about the backbone forking: I agree that we have to do something against the instability of underscores delivery. Breaking changes in minor is really bad. Not sure if we should fork Backbone. On the other hand, it would spread awareness and if enough users use it it may help to fix the issue. I remember few other libraries doing it. And hell, why else is io.js being done :)

**Comment by bazineta** [comment]
Events of the past few days have certainly shaken confidence in the maintenance of the libraries.  I think at this point a fork is the right thing to do if only to send a message.

**Comment by framerate** [comment]
Thanks for filling me in, guys. Here's my two cents:

I'm a heavy backbone user (I use it in every one of my projects) because I like to keep things lightweight. That being said I have used marionette where I deem it necessary.

I'm fairly certain that if Marionette forks backbone and becomes incompatible, I will not use it again. Nothing against you guys or the "message" you want to send... but Backbone is already a mostly stable and long standing project/name. Marionette's strength to the average user is that it extends a product they already love (in my opinion, maybe you guys feel stand-alone now). If you fork, I fear you'll become a competing standard and we already have enough Angular vs Backbone vs Ember vs Etc arguments in the community as is.

I urge you to just understand that @jashkenas made some mistakes and maybe should have consulted with his community since so many people depend on it. But he's already been seemingly invested in fixing it. Don't over complicate the community by forking. We have enough confusion as it is (node vs iojs, lodash vs underscore, python3 vs python4). Let's just work together and make one library the best we possibly can. I'll help any way I can.

![Imgur](http://i.imgur.com/KclmEo7.png)

**Comment by mattd** [comment]
+1 @framerate. I'm the *exact* same way. The fact that this conversation is even *happening* has me concerned.

**Comment by jmeas** [comment]
I'm locking this conversation, 'cause it doesn't *actually* directly involve Marionette. In fact, it shouldn't even be in the Marionette issue tracker.

As I understand it, the Backbone fork would be a separate project from Marionette. It would be a standalone project from the Backbone community. Given Marionette's standing in the Backbone community, many of the Marionette team members would contribute to the fork and make sure it stays active and healthy.

The purpose of the fork would not be to become backwards incompatible. Like Exoskeleton, one of the core virtues of the fork would be its swappability for regular ol' Backbone. So that is not a concern.

Anyway, this conversation should likely move to other channels.

**Comment by thejameskyle** [comment]
To add on to what @jmeas said, this isn't somthing Marionette is doing in isolation. https://gitter.im/marionettejs/bb_next/archives/2015/02/20

**Comment by samccone** [comment]
Going to close this for a now. We are protected from breaking changes simply by locking what versions of BB we use.

I echo what @jmeas said.
