### ISSUE TITLE
bindUIElements isn't called when template = false

### ISSUE THREAD

**Issue by scott-w** [marionettejs/backbone.marionette#2373]
When you extend a view with `template: false`, the values of `this.ui` are still strings, instead of jQuery selectors.

A current workaround is to call `this.bindUIElements()` in `initialize` but it would be better for Marionette itself to figure it out.

**Comment by samccone** [comment]
interesting @scott-w I know why we did this but I am guessing your case is where you are setting your view on a DOM element that is already on the page? Is that correct?

**Comment by jmeas** [comment]
Related: https://github.com/marionettejs/backbone.marionette/issues/1971#issuecomment-57963820

The source of this problem is that there are two broad types of views, and Marionette only handles 1 type.

The type that Marionette supports is that your element is created on-the-fly, or it already exists and is empty. These elements either have a template rendered into them, or they're a container for a graphic like an SVG.

The other type is an existing element that already has elements within it. Marionette doesn't do anything for this, which causes bugz.

**Comment by scott-w** [comment]
@samccone That's exactly my case :)

**Comment by samccone** [comment]
@scott-w would you like to open a PR to try a fix, not opposed to figuring out a nice solution

**Comment by scott-w** [comment]
I'll have a look tomorrow afternoon and see what I can come up with.

**Comment by samccone** [comment]
:+1:

**Comment by jasonLaster** [comment]
Nice find!

**Comment by scott-w** [comment]
This is in Marionette 2.1.0 by the way. I'll check it with 2.4.0.

**Comment by samccone** [comment]
I don't expect it to be fixed in 2.4. :)

**Comment by scott-w** [comment]
It appears to be fixed already, does someone want to have a quick look and see if I've done that test right?

Also, shall I send a PR with just this test?

**Comment by ahumphreys87** [comment]
test on #2381 is valid and passes. Closing

**Comment by andrewjmead** [comment]
Did this make it into 2.4.1? I'm still seeing this issue.
