### ISSUE TITLE
Discuss reverting getUi

### ISSUE THREAD

**Issue by thejameskyle** [marionettejs/backbone.marionette#2412]
Bad idea, poorly executed, [users don't like it](https://github.com/marionettejs/backbone.marionette/issues/2102#issuecomment-78059376).

**Comment by samccone** [comment]
We all know you are not a fan of this idea, per our normal pattern @jasonLaster myself and @ahumphreys87 are in agreement that this is not a bad thing, there is some discussion around it and the value that the abstraction really adds. I am going to close this issue but we can continue to talk about it. 

You have made you position very clear and two users have commented on the issue, I am in @jasonLaster 's camp, this is a nice thing and a nice interface and really quite low impact. 

@marionettejs/marionette-core would love to hear your thoughts

**Comment by stackptr** [comment]
I agree that there is merit in having consistency in the ui hash. As a relative newcomer to Marionette I ran up against this issue several times which introduced boilerplate into the project before I fully understood the problem. I don't think having `getUi` is significant overhead and adds some clarification to how to properly use the UI hash.

Past the added syntax, I wonder why it is considered poorly executed? Having proper errors thrown before render is way better, in my opinion, than having strings thrown out when you're expecting jQuery objects.

**Comment by thejameskyle** [comment]
As I said in the chat before, if the reasoning for this was to have a common interface for all config options, then Marionette should introduce a single `get` method for all of them which can deal with the ui hash, behaviors hash, etc.

But that was not the reason for this. The reasoning of protecting users from running into issues where the view has not yet been or is no longer rendered is a short sighted one that ultimately does not fix the issue and actually will make other things harder to track down. My response to that is simply learn how to debug javascript, we can't protect you from everything.

**Comment by stackptr** [comment]
>My response to that is simply learn how to debug javascript, we can't protect you from everything.

I disagree with this logic to the extent that you're using it. While a framework should not coddle its users, it should offer consistent interfaces that (in part) make debugging easier. What shouldn't happen is that the framework gets more complex to address edge cases, which doesn't seem to be the case here. And while maybe this is not the optimal solution and perhaps there should be a single get method as you say, this seems like a step in the right direction that doesn't involve any expensive complication. As for not fixing the issue, I wonder what that issue is and how it should be addressed? If this is simply a band-aid on a deeper problem then that is worth bringing up, but from what I see this seems to be a refinement on some existing functionality that was known to cause some users (like me) some problems. Could you cite the issues you're referencing that this doesn't fix?
