### ISSUE TITLE
revert array-syntax for behaviors

### ISSUE THREAD

**Issue by thejameskyle** [marionettejs/backbone.marionette#2413]
Really really bad for inheritence https://github.com/marionettejs/backbone.marionette/pull/2368#issuecomment-78166820

**Comment by samccone** [comment]
My response to your comment would be that if you are trying to inherit from a view that has behaviors and trying to mixin new behaviors you are in need of a more robust mixin strategy. 

Since behaviors can have grouped behaviors I would instead tell people to make a new base behavior that you would add to each view that needs it. 

On top of that, I never recommend extending and manually trying to inherit from your custom views because you will run into an entire class of problems that are best handled with a different approach.

**Comment by thejameskyle** [comment]
> My response to your comment would be that if you are trying to inherit from a view that has behaviors and trying to mixin new behaviors you are in need of a more robust mixin strategy.

There's no mixin strategy that could possibly account for this. This is a manual process.

> Since behaviors can have grouped behaviors I would instead tell people to make a new base behavior that you would add to each view that needs it.

Still doesn't solve the problem.

> On top of that, I never recommend extending and manually trying to inherit from your custom views because you will run into an entire class of problems that are best handled with a different approach.

_WHAAAA—_ Of course you should be able to inherit from custom views, if there are an entire class of problems then that's a problem with Marionette and should be addressed.

---

Even if suddenly Marionette was completely against inheritance (which is absurd), then it's still an issue of being a bad API. You shouldn't have multiple syntaxes for the same API when one will do. That's just a fundamental rule of API design.

**Comment by samccone** [comment]
Well, I am :-1: on reverting this, I think it was a good call per the normal patterns that we have been following on this project for over a year @jasonLaster and I were in agreement on the value that this adds. 

ping @marionettejs/marionette-core for thoughts


> WHAAAA— Of course you should be able to inherit from custom views, if there are an entire class of problems then that's a problem with Marionette and should be addressed.

I should clarify, once you extend from a view, you choose to nuke pieces of it, that is the norm and how marionette works, just like you can override events / ui / modelEvents / render ... ect ect. 

When I see someone in a code base manually trying to mixin the "super" props like you have above I question the value of what they are doing, why not create a new view class why do you need to mixin? Is there really that much shared code? If there is so much shared code it calls for a higher level abstraction and or a more generic base.

**Comment by thejameskyle** [comment]
> When I see someone in a code base manually trying to mixin the "super" props like you have above I question the value of what they are doing, why not create a new view class why do you need to mixin?

Because mixins are supposed to be composable, thats like... the whole point.

But as I've stated before, Behaviors are very far from mixins; and because of the lack of composability they really have become an anti-pattern.

**Comment by samccone** [comment]
> they really have become an anti-pattern.

Interesting perspective, I think they are the opposite, they encourage a powerful composable architecture. I know multiple companies have had huge wins with them and have had a positive impact on many code bases, but this all could be a sampling bias.

**Comment by thejameskyle** [comment]
>  they encourage a powerful composable architecture. 
>  ---
> if you are trying to inherit from a view that has behaviors and trying to mixin new behaviors you are in need of a more robust mixin strategy.

wat

**Comment by samccone** [comment]
That is what I said :)

**Comment by benmccormick** [comment]
Just wanted to toss in one final thought as the person who started this whole thing:

I see @thejameskyle's point that this adds complication to the inheritance scenario.  I hadn't considered it because I also don't inherit from user views, only directly from Mn base views, and then use behaviors to share code.  But I can see how this is inconsistent when viewed through that use case.  I think there are a few mitigating factors here though.

1. Behaviors are not on any base views, so this is only when inheriting from existing user views

2. Presumably inheriting from custom views would be in the context of a project.  IE, you're not just inheriting from a random set of views. Projects can have conventions of using one syntax or the other, or define a helper function to  handle the ugliness if you really want to have behaviors on a base view then add more.  Realistically "super" stuff for overriding hashes is a path to lots of ugly extends code no matter what.  It is easy enough to centralize.  

3. What I think this whole conversation is illustrating is that behaviors and inherited custom views tend to be 2 ways to achieve the same goal (sharing common view code between multiple views).  But I don't think they're helpful together.  I don't see a point in doing both.  That's illustrated a bit just by the issues you too seem to be having with each others approach

IE

> But as I've stated before, Behaviors are very far from mixins; and because of the lack of composability they really have become an anti-pattern.

Behaviors aren't useful if you're using inheritance to share code between views 

and 

> On top of that, I never recommend extending and manually trying to inherit from your custom views because you will run into an entire class of problems that are best handled with a different approach.

Inheritance isn't needed if you share all common view code using Behaviors.  

I've fallen more on the behavior side of this personally, but I don't think there's anything crazy with the inheritance way.  I do question the usefulness of behavior inheritance in that case though.  And this feature is clearly useful if you're relying heavily on Behaviors since it cleans the API up considerably.

Since inheritance is still possible I don't think its unreasonable to make the interface for a less common/useful scenario (inheritance/super of behaviors across custom views)  worse in order to improve the interface for a more common/useful scenario (multiple behaviors imported using modules) significantly better.
