### ISSUE TITLE
preventDestroy in layout is not working properly

### ISSUE THREAD

**Issue by chuchiperriman** [marionettejs/backbone.marionette#2415]
Setting preventDestroy with a layout is detroying childViews in the layout region. This is a test case

http://codepen.io/anon/pen/azRYqQ?editors=101

At start the list layout is shown in mainRegion. When click on detail, show DetailView in mainRegion (with preventDestroy: true). If click on back, the listLayout is shown again in mainRegion but marionette raises an error because the views inside de layout are destroyed (the views inside, not the layout)

**Comment by paulfalgout** [comment]
I believe the issue you're running into here is calling show again on the layout will re-render the layout.  re-rendering the layout will cause anything in its regions to destroy.  And the `preventDestroy` option you set is only in reference to the LayoutView itself in its region, not its children.

So if you wanted to go down this road you'd need to:
```js
this.layout.on('show', function(){
  this.sub1.show(sub1, { preventDestroy: true });
  this.sub2.show(sub2, { preventDestroy: true });
});
```

but honestly `preventDestroy` should have a very limited use-case.. You should ideally be destroying and rebuilding views.  Event if you decide to keep the layoutview around for some reason, its children are easy to fix in your codepen.

```js
this.layout = new Layout();
this.layout.on('show', function(){
  var sub1 = new SubView1();
  var sub2 = new SubView2();
  this.getRegion('sub1').show(sub1);
  this.getRegion('sub2').show(sub2);
});
```

**Comment by chuchiperriman** [comment]
But with the last change your are recreating the subviews on every show and the idea is keeping the views without destroy it.

I've changed the code to set the preventDestroy on subview show but the error persist:

``` javascript
this.layout.on('show', function(){
  this.sub1.show(sub1, { preventDestroy: true });
  this.sub2.show(sub2, { preventDestroy: true });
});
```

**Comment by paulfalgout** [comment]
> the idea is keeping the views without destroy it.

Maybe, but it's kind of a bad idea.  You should just recreate them.

The issue here is still that `preventDestroy` is only for the parent view for that `region`.
So before you hit this line again:
```js
App.mainRegion.show(this.layout); 
```
`this.layout` is still entirely intact with it's child views are intact and not destroyed.  You could easily append this.layout.$el and it'd be ready to go.

But when you show a view in a region, it renders that view first.  The render is rebuilding the regions of the layout.. rebuilding those regions is destroying the views inside them, so before the `on('show'` is called they're already destroyed.  You would run into the exact same issue here:

```js
App.mainRegion.show(this.layout); 
App.mainRegion.show(detailView, { preventDestroy: true });
this.layout.render();
// At this point, the layout's children are gonzo. 
```

Possibly there is an argument for a `preventRender` on a `region.show`, but you'd have to make it conditional and that's just continuing the `preventDefault` spaghetti patterns. I would be :-1: on that myself.  A region should not have to care if the view was previously shown and not destroyed.

If you're absolutely set on preventing the views in the layout from being destroyed you'll need to do this:
```js
list: function(){
  if (!this.layout){

    var sub1 = new SubView1();
    var sub2 = new SubView2();

    this.layout = new Layout();
    this.layout.on('show', function(){
      this.sub1.show(sub1);
      this.sub2.show(sub2);
    });
  }
  App.mainRegion.show(this.layout);
  App.mainRegion.once('before:swapOut', function(){
    this.layout.sub1.empty({preventDestroy: true});
    this.layout.sub2.empty({preventDestroy: true});
  }, this);
},
```
But that's not a good use for `swapOut`.

I took out the `preventDestroy`s in the `on('show'`  but if you ever plan to do anything else inside this layout's regions you may need to keep those in there.

But ping @marionettejs/marionette-core for a 2nd opinion.

**Comment by paulfalgout** [comment]
Actually, @chuchiperriman you might be served with this open PR https://github.com/marionettejs/backbone.marionette/pull/2335

**Comment by chuchiperriman** [comment]
Thank you very much for your help @paulfalgout !!
