### ISSUE TITLE
triggers with traceur

### ISSUE THREAD

**Issue by Urec2731** [marionettejs/backbone.marionette#2489]
```js
export class ItemView extends Marionette.ItemView {
    constructor(options) {
        super({
            template: "#item-template",
            tagName: 'section',
            model: options.model,
            className: "enter-the-class-name",
            attributes: {
                'data-section': ""
            },
            events: {
                'click .del-x': 'removeItem'
            }
        });
    }
    removeItem() {
        this.trigger('remove:me');
    }
}
work with
export class CollectionView extends Marionette.CollectionView {
    constructor() {
        super({
            collection: topics,
            childView: ItemView,
            emptyView: EmptyView,
            tagName: 'article'
        });
    }
    onChildviewRemoveMe (item) {
        this.collection.remove(item.model);
    }
}

but this code:
export class ItemView extends Marionette.ItemView {
    constructor(options) {
        super({
            template: "#item-template",
            tagName: 'section',
            model: options.model,
            className: "enter-the-class-name",
            attributes: {
                'data-section': ""
            },
            triggers: {
                'click .del-x': 'remove:me'
            }
        });
    }
}
```
do not work!

index.html =>
  <script type="text/javascript" src="lib/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="lib/underscore.js"></script>
    <script type="text/javascript" src="lib/backbone.js"></script>
    <script type="text/javascript" src="lib/backbone.marionette.js"></script>

    <script src="https://google.github.io/traceur-compiler/bin/traceur.js"></script>
    <script src="https://google.github.io/traceur-compiler/src/bootstrap.js"></script>

(edited by @cmaher for formatting)

**Comment by ahumphreys87** [comment]
@Urec2731 would you mind submitting your code example in the form of a jsfiddle? It should be easier for us to help like that

**Comment by Urec2731** [comment]
http://jsfiddle.net/uda4b6Lf/

**Comment by paulfalgout** [comment]
So the issue here is that triggers is being handed up as an option to the view, not as part of the view's prototype.

With Backbone, events is part of viewOptions that get attached to the view so:
```js
var view = new Marionette.ItemView({ 
  events: 'foo'
});

view.events === 'foo';  // => true
```
ref: http://backbonejs.org/docs/backbone.html#section-138

But triggers defined via options are not attached so:
```js
var view = new Marionette.ItemView({
  triggers: 'foo'
});

view.triggers === undefined; // => true
```

so in your case `this.triggers` is undefined and the don't get setup here:
https://github.com/marionettejs/backbone.marionette/blob/master/src/view.js#L71

However at that point in your code `this.options.triggers` is defined.

I would support a PR suggesting that `triggers` and `events` should behave similarly and that `triggers` like `events` should be attached via `options` on view creation.  However as it is currently, this is the expected behavior.
