### ISSUE TITLE
I can not listen the request event on modelEvents

### ISSUE THREAD

**Issue by diegoleme** [marionettejs/backbone.marionette#2497]
When I'm on an item View and use the modelEvents property does not work
```javascript
initialize: function(){
  this.model.fetch()
},
modelEvents: {
  'request': 'showLoader'
}
```

I have to use the listen on initialize
```javascript
initialize: function(params){
  this.listenTo(this.model, 'request', this.showLoader)
  this.model.fetch()
}
```

This is the expected behavior?

**Comment by paulfalgout** [comment]
It is expected behavior.

Currently events are delegated after the initialize occurs.
https://github.com/jashkenas/backbone/blob/1.1.2/backbone.js#L1002

The next version of Marionette has pulled entity events outside of `delegateEvents` but it continues the pattern of putting it after the `initialize`

https://github.com/marionettejs/backbone.marionette/pull/2241/files#diff-7249cd6f2a2b03a224634e69c0b37fbfR28

**Comment by diegoleme** [comment]
Tks @paulfalgout

**Comment by gdtrice** [comment]
:cry:
