### ISSUE TITLE
Hooks for transitions on CollectionView

### ISSUE THREAD

**Issue by Seebiscuit** [marionettejs/backbone.marionette#2553]
Came a across an interesting question on SO, that should've been more common: [Backbone.js model.destroy() custom transitions?](http://stackoverflow.com/q/29859400/2112866). The question deals with the life cycle of a collection model when it is destroyed. When the model emits a `'destroy'` event, the parent collection eventually causes the destruction of the model's corresponding ItemView.  What struck me was how difficult it is to run a transition on a model's `'destroy'` event. 

The issue turns up on the child view's `view.destroy()` method, as you can see this clearly in the source: 

```
destroy: function() {
    // ...

   // We implement an async transition here
    this.triggerMethod.apply(this, ['before:destroy'].concat(args));

    /// ..

    // But the animation is queued and sync .remove() gets called before
    //  the transition would
    this.remove();

    // ...
  },
```

DOM animations are run async, while the `View.destroy()` routine is run sync. So even if you implement the transition on `onBeforeDestroy`, the view's `.remove()` is called before the animation has a chance to reach the runtime queue. This is a thorny issue because of the async vs sync race (which sync will always win, by definition), making workarounds like those found in the SO question necessary.

Of course, the user can run the transition and queue the `model.destroy()` when the animation completes, but then we're forcing the user to *not* wait for the server response on the model (or at least to worry about handling an error response).

Are destroy transitions important enough that there should be some handling by the Mn core?

**Comment by ianmstew** [comment]
Hey @Seebiscuit!  So, one approach to deal with the sync/async issue is to invoke the original `destroy()` method from within your own custom `destroy()` override at the time of your choosing.  That way you don't have to copy paste the code from core.  You can do that with a superclass call:

```js
var MyItemView = Marionette.ItemView.extend({
  attributes: {
    style: 'opacity: 1'
  },

  destroy: function () {
    var originalArgs = arguments;
    this.doAnimation().done(_.bind(function () {
      // These two statements are identical, but both are shown to give you a better
      // idea what is going on by making a superclass call.  This is a useful Javascript
      // pattern to know.  __super__ is a convenience property supplied by
      // Backbone.extend().
      Marionette.ItemView.prototype.destroy.apply(this, originalArgs);
      MyCollectionView.__super__.destroy.apply(this, originalArgs);
    }, this));
  },

  doAnimation: function () {
    var deferred = $.Deferred();
    this.$el.css({
      opacity: 0,
      transition: 'opacity 0.2s linear'
    });
    // You could use a more sophisticated "transition end" approach here that relies
    // on browser transitionend events, but this should be sufficient unless you are
    // interested in chaining multiple transitions.
    _.delay(function () {
      deferred.resolve();
    }, 250);
    return deferred.promise();
  }
});
```

As far as hooks for transitions in core, I would like to hear what others think.  Thanks for starting the discussion!

**Comment by Seebiscuit** [comment]
Hey @ianmstew. This is definitely a possibility, but it makes the decision for you that you're not going to wait for the server. But I'll grant you that unless we start thinking of including Promises into the core we're not really set up to handle things like this.

**Comment by ianmstew** [comment]
@Seebiscuit That's definitely true, but it might not be a concern.  One way to look at it is that the view's only job is to reflect the state of the models, so if a model says "destroy" then it's time to destroy (or start the destroy transition).  If you'd rather the views didn't transition until the server confirms, that can be handled on the model side with the `{wait: true}` option to the model.destroy() method.

What would be awesome, though, are hooks that would allow something like @jmeas' [transition region](https://github.com/jmeas/marionette.transition-region) without needing to override the entire `Region#show()` method.  Based on the current hooks he had no choice but to reimplement `show()`.

**Comment by ianmstew** [comment]
@Seebiscuit, @jmeas is contemplating what an animation framework for Marionette might look like.  You two might have some things to talk about along these lines on a new thread.  For now I'm going to close this one!

**Comment by jmeas** [comment]
My idea hasn't been thought through too thoroughly, and it might not even be much better than just using basic jQuery shtuff. But the idea is that you would register an animation like so...

```js
Mn.registerAnimation('slideOut', function($el, done) {
  $el.animate(animationDefinition, done);
});
```

Then, in your code...

```js
myView.animate('slideOut');
```

The `animate` method would behave similarly to async Model methods, in that it would:

1. return a Promise
2. emit an event on completion (of the form `animationName`);

===

So you could do...

```js
myView.animate('slideOut')
  .then(() => {
    parentView.showChildView('somePlace', newView)
  });
```

Is this a good idea? I'm not sure tbqh. But I like that it abstracts away the animation definitions, supports JS and CSS animations, and provides a uniform interface for animations of any kind.

If `Region#show` was updated to allow for you to either append **or** replace the element, then this would allow for animating in and out at the same time, too.

**Comment by billyjanitsch** [comment]
@jmeas I'm curious why you prefer this approach to that of something more like your [transition region](https://github.com/jmeas/marionette.transition-region) prototype.

I like the idea of registering custom animation functions with a callback to call on completion (especially if they can also be called by reference instead of by name/global registration to fit nicely into module loaders).

However, it seems more sensible to declaratively tell a parent view how to animate in/out its children views in a particular region so that you can transparently call `show()` and `empty()`. I don't think I'd want my child view explicitly telling its parent when, let alone what, to render in its place -- that seems like a lot of knowledge the child view shouldn't have. Plus, it requires that extra boilerplate every time you want a view to do this.

You could instead give regions optional `animateIn` and `animateOut` properties, which could be set to one (or more) animation functions, and when you `show` and `empty` in that region, it waits for all animations out before destroying the view and beginning the animations in. You could also have a concurrent flag to modify that behavior.

Alternatively (or as well), give all views optional `animateIn` and `animateOut` properties, such that when a parent view shows/hides a child view in a region, the parent checks the child for these properties and obeys them if they exist.

**Comment by jmeas** [comment]
> @jmeas I'm curious why you prefer this approach to that of something more like your transition region prototype.

I've had a hunch lately that Regions might be an unnecessary abstraction that users of Marionette shouldn't have to deal with, so I've been exploring that lately in my own applications. I've been liking it a lot. The system described above lets me do animations without working with Regions directly.

> (especially if they can also be called by reference instead of by name/global registration to fit nicely into module loaders).

That could work, too. I use a module loader but I'd still opt for the global registration approach :P

> I don't think I'd want my child view explicitly telling its parent when, let alone what, to render in its place -- that seems like a lot of knowledge the child view shouldn't have.

Yeah, I don't think this is a good idea, either. I get the sense that you're drawing this situation from the example I posted...I just threw some random view names into the example to demonstrate the API.

The important thing to note is that it emits a Promise and an event. Devs could structure how they use that API however they want.

> ...declaratively tell a parent view how to animate in/out its children views in a particular region...

My concern with this is that there might be times when you want one animation, and times when you want another. Sure, the config hash could accept a method...but that's just ugly, I think. My preference would just be that you specify methods that handle each transition on the parent view, then you call those methods when ya' need to.

===

Also, fwiw, I don't plan to push any of these ideas on Marionette core. It's mostly just me experimenting in my free time :P

**Comment by billyjanitsch** [comment]
> Also, fwiw, I don't plan to push any of these ideas on Marionette core. It's mostly just me experimenting in my free time :P

I think it would be cool to see some of this in core or as a plugin (seems to be often requested, and there's not a simple way to do this nicely yourself), but I can understand reasons not to. I'm also just playing with this in my free time, trying to come up with an API that I'm happy with.

> I get the sense that you're drawing this situation from the example I posted...I just threw some random view names into the example to demonstrate the API.

So, as a more realistic example, say I want a parent view to switch from one child to another. Is the idea that the parent would get its child view, call an animate method on it, and when the returned promise resolves, call its own show method to show a new child, which then has some animation login in its `onAttach`?

That doesn't seem like the best separation of concerns between parent and child. I can imagine scenarios where you'd want either the parent or the child to decide what sort of child animation happens either for animation in or out (or combinations thereof). It seems hard for the parent to tell the child how to animate in, and for the child to tell itself how to animate out. All *possible*, but not without writing methods all over the place (overwriting `destroy` with a super call, `onAttach`, patching `show`/`empty`, etc.), unless I'm missing something.

I really like the idea of a more consistent and declarative solution that just lets you call `show`/`empty` on the parent, with animation options pre-configured on the parent and/or child (100% separately) as needed, and handles the promise magic for you.

> My concern with this is that there might be times when you want one animation, and times when you want another. Sure, the config hash could accept a method...but that's just ugly, I think.

Is it ugly? I don't see it as very different from e.g. `getTemplate` -- it's a little clunky but makes semantic sense and doesn't get used often enough to clutter up your code. Definitely a valid concern, though.

> The important thing to note is that it emits a Promise and an event. Devs could structure how they use that API however they want.

Nit: not sure about the event being the animation name, since I can imagine using the same animation in different contexts in the child view, and I wouldn't want to write logic to figure out the context on the handler.
