### ISSUE TITLE
showChildView() options

### ISSUE THREAD

**Issue by jbarreiros** [marionettejs/backbone.marionette#2572]
I have a situation where I have a region and its view can be one of two Views, which may be swapped later.

```
onRender: function() {
    var view = this.textView;
    if (model.get('someproperty') === true) {
        view = this.formView;
    }
    this.showChildView('myregion', view, {preventDestroy: true});
},
onDestroy: function() {
    this.view1.destroy();
    this.view2.destroy();
}
````

Turns out `showChildView` does not take an `options` hash. Is this by design?

**Comment by paulfalgout** [comment]
I think it was likely an oversight.  I'd love to see a PR for this.  If you're up for it, please PR against the `next` branch.

**Comment by ianmstew** [comment]
@jbarreiros Any progress on a PR?

@paulfalgout Considering this is an oversight, it could be argued into a patch release.  Considering it is also an addition, it could argued as a feature.  I lean toward the oversight argument and would like to see this sooner rather than later.  What do you think about a PR for this against `patch` for `2.4.3`?

**Comment by ianmstew** [comment]
Nvm, I somehow missed the PR.
