### ISSUE TITLE
View LifeCycle Monitor

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#2737]
We should replace `onDOMRefresh` with a full view lifecycle monitor.

And it should have it's own event handling such that it can `listenTo` views given to it.

It should handle the render, attach (maybe detach) (along with an onDomRefresh)
(also assuming region show events are no longer triggered on the view)

It would replace view internal listeners:
https://github.com/marionettejs/backbone.marionette/blob/v2.4.2/src/collection-view.js#L30

so if you were to `view.off('attach')` you would not break the view's internal functionality.

Additionally this would allow you to reasonably add view lifecycle events to a `Backbone.View`.

Thoughts?

**Comment by paulfalgout** [comment]
Very related to https://github.com/marionettejs/backbone.marionette/issues/2560

**Comment by JSteunou** [comment]
Great idea! Abstraction abstraction abstraction!

**Comment by jasonLaster** [comment]
I think this could be a nice abstraction too. Mind sharing s small gist of what the implementation would look like.

**Comment by ianmstew** [comment]
This seems like a good idea, but I can only see this making sense for firing "contingent" events--events based on other events--or tracking state of a view with flags in one place (`isRendered`).  I don't see such a listener as capable of _firing_ events such as `render` on views, because these are bound to imperative code within views.

**Comment by paulfalgout** [comment]
Agreed.

**Comment by paulfalgout** [comment]
Closed by https://github.com/marionettejs/backbone.marionette/pull/2850
