### ISSUE TITLE
Plugin ecosystem

### ISSUE THREAD

**Issue by ianmstew** [marionettejs/backbone.marionette#2741]
A number of features are coming that could be quite useful to many people, and yet might not fit the definition of "core".  Some examples:
- Filtered/sorted CollectionViews (already in core, but could become a plugin instead)
- incremental-dom support
- Component notation in templates (#2734)
- UI-state-aware views

What would an "officially supported" plugin ecosystem look like; e.g., could plugins be published underneath the `dist` folder for optional inclusion by apps?

**Comment by ianmstew** [comment]
Relevant: https://github.com/babel/babel/blob/development/doc/design/monorepo.md

**Comment by rogovdm** [comment]
Sounds good. Pluggable core — always sounds good.

**Comment by Seebiscuit** [comment]
The model is great since it bakes standards for plugin dev. But, playing devil's advocate, is the limited development, which is the cost of better quality, hurt Bb/Mn adoption?

A quick word about this issue, which has been on my mind as of late. I'm developing a position where a small, limited, non-existent (too harsh?) plugin library is seriously hurting Bb/Mn adoption. Rewriting the wheel each time may be a deal-breaker for project managers. Worse, a well developed Plugin may also deal with all those itchy edge cases that end up consuming 80% of our time. Plugins are the way to put our collective knowledge in one place, keep the core slim, and widen access to the framework.

Following Mn since Derrick used to be running things, to seeing how its growing with the new Mn core contributors, I think Mn is reaching the maturity to start a Plugin repo (ala Babel, or beyond).

Can we widen this discussion? cc: @jmeas, @thejameskyle, @cmaher, @samccone
