### ISSUE TITLE
LayoutView childEvents: Allow for filtering based on region.

### ISSUE THREAD

**Issue by MeoMix** [marionettejs/backbone.marionette#2783]
Consider the following:

```
var ConfirmDialogView = Marionette.LayoutView.extend({
    template: false,
    onShow: function(){
        this.triggerMethod('dialog:confirm', { result: 'Ok' });
    }
});

var FooView = Marionette.LayoutView.extend({
    template: _.template('<div data-region="dialog1"></div><div data-region="dialog2"></div>'),

    regions: {
        dialog1: '[data-region=dialog1]',
        dialog2: '[data-region=dialog2]'
    },

    childEvents: {
        'dialog:confirm': '_onChildDialogConfirm',
    },

    onRender: function(){
        this.showChildView('dialog1', new ConfirmDialogView());
        this.showChildView('dialog2', new ConfirmDialogView());
    }

    _onChildDialogConfirm: function(options){
        console.log('Confirm result:', options.result);
    }
});
```

It would be nice to be able to filter whether an event comes from the dialog1 or dialog2 region. Similar to in 'events' where the selector filters how/when event handlers run.

This would allow for:

```
childEvents: {
    '@region.dialog1 dialog:confirm': '_onRegion1DialogConfirm',
    '@region.dialog2 dialog:confirm': '_onRegion2DialogConfirm'
}
```

**Comment by russplaysguitar** [comment]
:+1:

**Comment by Tranfu** [comment]
:+1:

**Comment by msiconolfi** [comment]
So I have a preliminary PR for this feature. Should I branch off of next for this? I don't see a `layout-view.js`. Did this get moved into something?

**Comment by msiconolfi** [comment]
It looks like on `next` `Marionette.AbstractView` is what  `Marionette.View` was and `Marionette.View`is now what `Marionette.LayoutView` was?

**Comment by jasonLaster** [comment]
I would prefer dropping the `@region.dialog1` in favor of `@dialog1`. 

In general I'm afraid of this pattern slightly because I would prefer `dialog:confirm` would be replaced with something action specific like `form:saved` `form:updated` where there's context and verb... but I'm not sure I'm necessarily opposed to this idea either.

**Comment by paulfalgout** [comment]
Now that proxying view events is normalized between View and CollectionView I think this would be abnormally difficult to implement in any sort of performant fashion on a very very hot function.

We should not do this. :-1:

However I think a moderately simple behavior can handle the use-case

https://jsfiddle.net/g9znf174/

Alternatively you can always deal with it, quite easily, in the handler:
```
onChildViewRender: function(view) {
  if (this.getChildView('foo') !== view) return;
}
```

**Comment by rally25rs** [comment]
I would really like this behavior to be available in some way. I do think having the child view events wired into `view.events` hash is the most logical way, since using Marionette you sort of train yourself to look at that hash to see what events are handled. My initial thought was very similar to the one originally proposed here, mirroring how events handles UI elements, doing something like:

```
regions: {
  things: '[data-region="things"]'
},

events: {
  'change @region.things': 'onThingsChanged'
}
```

but I can certainly appreciate the complexity of implementing that, since any time the child view changes, the event handlers would have to be cleaned up and re-added to changing views.

Perhaps the `showChildView` function could be extended to take in more options, like events?

```
Marionette.View.extend({
  regions: {
    things: '[data-region="things"]'
  },

  onRender() {
    this.showChildView('things', new SomeChildView(), {
      events: {
        change: 'onThingsChanged'
      }
    });
  },

  onThingsChanged(changeEvent) {
    ...
  }
});
```

internally I think `showChildView` could just iterate over `events` and call `this.listenTo()` for each key.
