### ISSUE TITLE
Is there a clean way setup a component view that wraps and augments an element?

### ISSUE THREAD

**Issue by rafde** [marionettejs/backbone.marionette#2822]
This as simple as I can get a working example to demo what the problem is.
I have this example:
http://codepen.io/rafde/pen/zveqjb
where `MyLayout` has`input.wrapTarget` which is an element that can only be wrapped because, for example, that element can be configured to appear or not appear in the template in accordance to the user's preferences.
The `WrapLayout` is a component view that will augment `input.wrapTarget` which gives the `input` list filtering capabilities base on what the user types. The user can click on one of the items in the list, which will output that item's text into `MyLayout#ui.selectedValue`

Any time I want to use `WrapLayout`, I have to do a `setupWrap` looking function for all the view that need to wrap the element and setup up listeners for the parent view (view that instantiated it). Anytime I want to create a `WrapLayout` type view and use it, I also have to include a `WrapLayout.wrapper` function that has to listen to the parent get destroyed (althought it should check to see if it's `el` is part of the `document`. This creates a lot of setup patterns. Any thoughts on how this could be done cleanly? Or anyone need more clarity regarding the issue?

**Comment by msiconolfi** [comment]
I'm still a little unclear on what you are trying to achieve. 
Also, in your example you are executing the `WrapLayout.wrapper` function on the prototype object`WrapLayout` did you mean to have that be on an instance using `new` or did you just want the wrapper functions to live in some object not necessarily a `LayoutView`

From what I see so far you might be able to use `Marionette.Behaviors` to mixin this type of wrapper behavior. Have you tried that yet?

**Comment by jasonLaster** [comment]
Thanks @msiconolfi curious if Behaviors will help you out here, it seems like the ideal usecase

**Comment by rafde** [comment]
@msiconolfi I have it as a behavior as well and the Component View can be shown as a view or it can wrap an element the way I have in the demo.
But I guess the point is that the behavior should be doing all that extra setup.

**Comment by msiconolfi** [comment]
I gave a it a second look and I think you can make your behavior as follows:
```javascript
window.Behaviors = {};
window.Behaviors.WrapperBehavior = Marionette.Behavior.extend({
  initialize: function(options) {
    // store the target selector
    this.targetSelector = options.target;

    // create an alias for parent view
    var parentView = this.view;

    // store the wrapLayout on the view
    this.view.wrapLayout = new WrapLayout(options.viewOptions);

    // bind wrapped layout events to parent view handlers by string name
    // NOTE: this could be fancier and determine if handler is a string or function
    _.each(options.events, function(handler, event) {
      var parentViewHandler = _.bind(parentView[handler], parentView);
      parentView.listenTo(parentView.wrapLayout, event, parentViewHandler);
    });
  },
  onRender: function() {
    // alias some variables
    var options = this.options;
    var parentView = this.view;
    var wrapLayout = this.view.wrapLayout;

    // render the wrapped layout
    wrapLayout.render();

    // get the target from the parent view
    $target = parentView.$el.find(this.targetSelector);
    $target.addClass('wrapInput');

    wrapLayout.$el.insertAfter($target);

    // Replace the input already rendered in this view with target one.
    wrapLayout.ui.input.replaceWith($target);
    wrapLayout.ui.input = $target;
  },
  onDestroy: function() {
    // destroy the wrapLayout when the parent view is destroyed
    this.view.wrapLayout.destroy();
  }
});

Marionette.Behaviors.behaviorsLookup = function() {
  return window.Behaviors;
}


var MyLayout = Marionette.LayoutView.extend({
  el: '.layout:first',
  template: false,
  ui: {
    wrapTarget: '.wrapTarget',
    selectedValue: '.selectedValue'
  },
  behaviors: {
    WrapperBehavior: {
      target: '.wrapTarget',
      viewOptions: {},
      events: {
        wrapSelected: 'onSelectedValue'
      }
    }
  },
  onSelectedValue: function(value) {
    this.ui.selectedValue.text(value);
  },
});

// Just need it to render
(new MyLayout()).render();
```
See the [forked codepen here](http://codepen.io/anon/pen/wKOKPj)

I took some liberties in defining some behavior config items, but based on how your example worked and (how other views might use the behavior) I added a `target` argument and an `events` hash. 

The `target` is where us can define your wrapped target. In your original code you used the UI alias `this.ui.wrapTarget`. For simplicity, I put the literal selector in there, but you can use `Marionette.normalizeUIValues` in the behavior to make that fancier if you'd like.

The events is just an extra feature I made so you didn't have to have the additional `listenTo(this.wrapLayout,....`. I was aiming to make it similar to `childEvents` or `collectionEvents`

But the parts that make the code simpler than your example is that you don't need to have the wrapper function anymore. You don't need a complicated `listenTo` handler. Since Behaviors are mixed-in you can simply define your own `onRender` and `onDestroy` on the `Behavior` and do all your wrapping logic in there.

Also, not sure if this was intentional, but in your example every time `MyLayout.render()` is called it creates a new `WrapLayout`, I moved the `WrapLayout` creation into the `Behavior`'s `initialize()` since that is called when `MyLayout.initialize()` is called.

Sorry for the long post, I hope this helps.

**Comment by rafde** [comment]
Nice... I'll probably augment this a bit and post it as a gist or something in case anyone wants to use this behavior... but I don't know where I could place it so people can see it. Thanks for the response.

**Comment by rafde** [comment]
Closing since this was answered. I will post a gist of the behavior at some point.
