### ISSUE TITLE
CollectionView.reorder() should add new models instead of re-rendering itself

### ISSUE THREAD

**Issue by msiconolfi** [marionettejs/backbone.marionette#2829]
This is for Marionette 2.4.4. 

In the reorder function we determine if there are `anyModelsAdded` after we have applied the `_filteredSortedModels()`, and if there are new models, then we re-render the whole `CollectionView`.

_Current Code:_

``` javascript
    var models = this._filteredSortedModels();
    var anyModelsAdded = _.some(models, function(model) {
      return !children.findByModel(model);
    });

    // If there are any new models added due to filtering
    // We need to add child views
    // So render as normal
    if (anyModelsAdded) {
      this.render();
    }
    //...
```

 I feel like a whole `CollectionView.render()` is not necessary. We should be able to treat this similar to an `_onCollectionAdd`. 

I am in the process of putting a Pull Request together but the patch branch does not currently have 2.4.4 on it yet. 

Here are my preliminary changes:

``` javascript
 // Reorder DOM after sorting. When your element's rendering
  // do not use their index, you can pass reorderOnSort: true
  // to only reorder the DOM after a sort instead of rendering
  // all the collectionView
  reorder: function() {
    var children = this.children;
    var models = this._filteredSortedModels();
    var modelsAdded = _.filter(models, function(model) {
      return !children.findByModel(model);
    });

    // get the DOM nodes in the same order as the models
    var elsToReorder = _.map(models, function(model, index) {
      var view;
      if (_.contains(modelsAdded, model)) {
        // if this model is one of the added models
        // then first add its child view
        var ChildView = this.getChildView(model);
        view = this.addChild(model, ChildView, index);
      } else {
        // otherwise get the view by it's model
        view = children.findByModel(model);
        view._index = index;
      }
      return view.el;
    }, this);

    // find the views that were children before but arent in this new ordering
    var filteredOutViews = children.filter(function(view) {
      return !_.contains(elsToReorder, view.el);
    });

    this.triggerMethod('before:reorder');

    // since append moves elements that are already in the DOM,
    // appending the elements will effectively reorder them
    this._appendReorderedChildren(elsToReorder);

    // remove any views that have been filtered out
    _.each(filteredOutViews, this.removeChildView, this);
    this.checkEmpty();

    this.triggerMethod('reorder');
  },
```

**Comment by paulfalgout** [comment]
So patch should have `2.4.4` on it.  You might just need to refetch from origin.

That aside, I'm not totally sure of the changes or if they're breaking, but what seems like a related issue is: https://github.com/marionettejs/backbone.marionette/issues/2723

One thing that concerns me a bit..  reorder and filter were features simultaneously added in parallel by different authors.  The edge cases and expected behavior when mixing them have been one thing after the next.  I'm certainly hoping we can reduce the overall complexity, even if that means extracting this functionality somehow.. otherwise we need a really solid grasp of how modifying one thing will affect the other.
