### ISSUE TITLE
Marionette with es6 strict mode not work well

### ISSUE THREAD

**Issue by rimlin** [marionettejs/backbone.marionette#2866]
I am using Webpack with babel-loader, what have preset `es2015`, and i see this trouble: when including Marionette (v.2.4.3) `es2015` preset change `this` agrument in [/lib/core/backbone.marionette.js:26][1] to `undefined` instead `this`. But this argument take `root` variable ([line 10][2]) and he see, what argument is `undefined` (not `this`) and output error. 

I see, what in `es2015` preset including `babel-plugin-transform-es2015-modules-commonjs`, what include `babel-plugin-transform-strict-mode`, which response for strict mode and close es6 modules.

  [1]: https://github.com/marionettejs/backbone.marionette/blob/master/lib/core/backbone.marionette.js#L26
  [2]: https://github.com/marionettejs/backbone.marionette/blob/master/lib/core/backbone.marionette.js#L10

**Comment by paulfalgout** [comment]
Yep so I believe this is a result of UMD and babel-loader.
Check out https://phabricator.babeljs.io/T3055

I'm not sure what the work around here is.  Essentially if you need to `allowTopLevelThis` for any UMD library, you're going to need to not use the es2015 preset since you'll have to add the option directly to the `babel-plugin-transform-es2015-modules-commonjs`

**Comment by paulfalgout** [comment]
If there's any further info on this I'd like to look into it.  It's possible we want to be exporting a cjs only version or utilizing `jsnext:main` or something, but otherwise I don't think this is anything specifically related to Marionette, and more related to how babel interacts with UMD.  Let's re-open this if there's more to investigate.
