### ISSUE TITLE
Different type of properties in ui object in CompositeView and CollectionView

### ISSUE THREAD

**Issue by denar90** [marionettejs/backbone.marionette#2891]
Hi. I'm using latest version of mt. 
Here is problem - http://jsfiddle.net/denar90/hycjk855/1/
In `CollectionView` `ui.test` is string, but in `CompositeView` it's an object (take a look at console). It's a bit confused. It happens because of [this line in CompositeView](https://github.com/marionettejs/backbone.marionette/blob/master/src/composite-view.js#L101-24)
`bindUIElements` applies for all `ui` elements also if there are not present in template.
Does it make sense to check if ui element present in template before calling `bindUIElements` and apply  it only for elements which are present in template?

**Comment by vinnymac** [comment]
@denar90 in the [docs](http://marionettejs.com/docs/v2.4.4/marionette.view.html#viewbinduielements) it states that this is already handled for `ItemView` and `CompositeView`. It also explains what you need to do in order to use this in other views such as the `CollectionView` where it isn't handled by default.

Just call `this.bindUIElements()` in the render method of that view.

**Comment by denar90** [comment]
Got it.
