### ISSUE TITLE
Region and CollectionView housekeeping

### ISSUE THREAD

**Issue by ianmstew** [marionettejs/backbone.marionette#2895]
A bit of housekeeping following #2850.

- [x] Add test to check that detach for an entire tree occurs before descendants are destroyed
- [x] ~~Shore up test coverage on CollectionView and Region.~~
- [x] Move `monitor-view-events` to `utils` or [some alternative] (https://github.com/marionettejs/backbone.marionette/pull/2850#discussion_r47015703).
- [x] Decapitalize MonitorViewEvents.
- [x] Create docs update ticket for API changes
- [x] Finalize [`_isDestroyed` call](https://github.com/marionettejs/backbone.marionette/pull/2850#discussion_r52967579) and potentially remove comments [like these](https://github.com/marionettejs/backbone.marionette/blob/next/src/object.js#L44).

**Comment by paulfalgout** [comment]
Test coverage can go https://github.com/marionettejs/backbone.marionette/issues/2581

**Comment by JSteunou** [comment]
Might be room for region optimization. I see in the constructor `this.el` [can be String or Object](https://github.com/marionettejs/backbone.marionette/blob/next/src/region.js#L23) then `this.$el` [is created](https://github.com/marionettejs/backbone.marionette/blob/next/src/region.js#L32), but can be `length === 0`. Why [calling `getEl` again](https://github.com/marionettejs/backbone.marionette/blob/next/src/region.js#L107) in the `_ensureElement` called by `show` and why condition it to `this.el` being a String? `this.el` could be a String but as I see in the constructor `this.$el` could already be fine. This make region use jQuery selector a recreate `this.$el` one time too many. I would understand a condition with `this.$el.length === 0`.

**Comment by paulfalgout** [comment]
I've been looking into this a bit..  as it is, it does attempt to not recall the `getEl` inside `_ensureElement`, but it is almost never effective at doing so.
most of the time the `$el` isn't available when the region is created, and the regions stick around on re-renders of the layout so it has to get recalculated possibly at the moment you need it.

I think it may actually be better to remove `_ensureElement` and have the region require the $el in DOM at instantiation..  and this would mean a smarter layout that would build the regions on the view's render, or even better perhaps at the point of `getRegion` The 2nd option is nice, but it might mess with people who are using regions beyond a simple container.  Then instead of keeping the region around a resetting it, they're just destroyed and rebuilt on subsequent renders.. (or again even better. detached / reattached and destroyed if they can't find the el they need)

**Comment by paulfalgout** [comment]
Related I started playing with making regions a bit more sane here: https://github.com/paulfalgout/backbone.marionette/commit/83d7b8b8cc33f4b01833a0a070495f23a8efeb7c

**Comment by denar90** [comment]
@ianmstew can task `Move monitor-view-events to utils or some alternative.` be done in scope of #2858 ?

**Comment by paulfalgout** [comment]
yes I think it can.

**Comment by denar90** [comment]
Can we close this one and add tests in scope of #2581 ?

**Comment by paulfalgout** [comment]
These test don't change coverage
