### ISSUE TITLE
Issue with routing after Backbone 1.2.3

### ISSUE THREAD

**Issue by davestevens** [marionettejs/backbone.marionette#2934]
I noticed an issue with routes not triggering when using the latest version of Backbone.
The below code works when using Backbone 1.2.3 but does not trigger with 1.3.1 or 1.3.2.

The commit which breaks it is: https://github.com/jashkenas/backbone/commit/3c6fabbc8fdc801cf32cf0090b7dc17f14691982 and its the change to backbone.js.

```javascript
import $ from "jquery";
import Backbone from "backbone";
Backbone.$ = $;
import Marionette from "backbone.marionette";

let App = new Marionette.Application();

App.on("before:start", () => {
  let Router = Marionette.AppRouter.extend({
    appRoutes: {
      "*default": "defaultRoute"
    }
  });

  new Router({
    controller: {
      defaultRoute: () => alert("defaultRoute")
    }
  })
});

App.on("start", () => {
  Backbone.history.start();
});

App.start();
```

**Comment by paulfalgout** [comment]
This is because Marionette has a fixed dependency on Bb, so whatever you're using to package your scripts is importing BB 1.3.2 for your use, and then Marionette is using 1.2.3 internally.

Mn `2.4.5` is in the works to support Bb `1.3.2` and in Mn `v3` this issue will likely go away as _ and Bb will be peerDependencies

**Comment by davestevens** [comment]
Okay, thanks for the quick reply.
