### ISSUE TITLE
Mn 2.4.5 when using with BB 1.3.2 fails to bind add/remove/reset/sort at _initialEvents

### ISSUE THREAD

**Issue by avipinto** [marionettejs/backbone.marionette#2965]
in v2.4.5 ( https://github.com/marionettejs/backbone.marionette/blob/master/changelog.md#v245-view-commit-logs )
the dependency on Backbone was updated to 1.3.2
if you use it instead of Backbone 1.2.1 - 
At CollectionView at _initialEvents this.collection is always undefined, so collectionview's automatic rendering stopps working  ( http://marionettejs.com/docs/v2.4.5/marionette.collectionview.html#collectionview-automatic-rendering ).
guess it relates to "Fixed a bug where Events.once with object syntax failed to bind context." at BB 1.3.2 since _initialEvents is bound at the CollectionView's ctor using this.once('render', this._initialEvents); 

you can play with it here http://codepen.io/avipinto/pen/JXrKgr?editors=1010

**Comment by Aure77** [comment]
Same issue. collection is undefined here : https://github.com/marionettejs/backbone.marionette/blob/11dc5511bbe812c54a0f25f40ea4b8af378bcbcf/src/collection-view.js#L89
because options haven't been processed in ctor before (https://github.com/marionettejs/backbone.marionette/blob/11dc5511bbe812c54a0f25f40ea4b8af378bcbcf/src/collection-view.js#L25)

**Comment by paulfalgout** [comment]
This is a bug in Backbone's minified version:  https://github.com/jashkenas/backbone/issues/3993

Updating the codepen to use the non-minified version, fixes this issue.
