### ISSUE TITLE
2.x should support Bb 1.3.x

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#2977]
Backbone is getting better about non-breaking changes _at least_ on the "patch" number.  We should remove the headache of the patch release cycle.

**Comment by just-boris** [comment]
+1.

Backbone 1.3.3 is out and they say in [their changelog](http://backbonejs.org/#changelog)
> Note that 1.3.3 fixes several bugs in versions 1.3.0 to 1.3.2. Please upgrade immediately if you are on one of those versions.

But I can't upgrade immediately because Marionette package strictly depends from earlier Backbone.

**Comment by JSteunou** [comment]
Dont say you cannot, there is always a way :) And Marionette users, myself first, were very happy to have a fixed version of Backbone when it pushed breaking changes without following semver.

**Comment by just-boris** [comment]
@JSteunou, so how you are going to get this?

When I do `npm install backbone backbone.marionette`, I am getting the following dependency tree:

```
├─┬ backbone@1.3.3
│ └── underscore@1.8.3
└─┬ backbone.marionette@2.4.5
  ├── backbone@1.3.2
  ├─┬ backbone.babysitter@0.1.11
  │ └── backbone@1.3.2
  └─┬ backbone.wreqr@1.3.6
    └── backbone@1.3.2
```

There are two different versions of Backbone: 1.3.2  and 1.3.3. That means that my application would include both of them when I build this with webpack and it blow up, because `Backbone.Model !== Backbone.Model` sometimes. It is very hard to figure out actual reason of bug and fix it.

**Comment by JSteunou** [comment]
To give an example I'm still with backbone 1.1.x because 1.2.x introduce a breaking changes I can handle now without a massive refactoring. So I just do `npm install backbone@1.1.x backbone.marionette` and then alias backbone to node_modules/backbone in my webpack config so every modules requiring backbone get the same.

**Comment by paulfalgout** [comment]
@just-boris the npm version of Bb 1.3.2 and Bb 1.3.3 are identical aside from the version number.  In Bb 1.3.2 only the minified file had an issue

**Comment by paulfalgout** [comment]
There is no issue supporting older versions of Backbone. Only versions outside of the range listed in Marionette
