### ISSUE TITLE
v3.0.0-pre.2 docs inconsistent and wrong without any warning

### ISSUE THREAD

**Issue by curzonj** [marionettejs/backbone.marionette#3002]
the v3.0.0-pre.2 docs are up and v3.0.0-pre.2 is the recommended download, but the documentation says different things in different places and some parts are just plain wrong. But no where does it say that it's a work in progress or a warning that it might be inaccurate. I have to start with 2.4.5 because the 3.0 docs are not usable yet for me to learn marrionette.

**Comment by ryan-farmer** [comment]
I hope this doesn't come across the wrong way or is out of line for not being a marionette contributor, but I feel compelled to respond only because, fwiw and imo, this speaks to the state of a lot of js dev at the moment. Specific to Mv3 I'll agree the move towards Mv3 feels disjointed. This is probably related to network effect as it pertains to development more than a fault of any given aim of Mv3.

If you are new to Marionette I'd recommend joining the Marionette gitter and asking specific questions you have. 2.5 years in I'm happy to help with most questions of a general how to nature you may have. 

Your observation is certainly valid and you aren't alone. This kind of feedback is more common these days. Angular 2.0 and React, even with their huge financial backings, are struggling with some of the same things regarding documentation and/or lifecycle translations. Life as a js dev these days, like life itself, is far from perfect. We are suffering growing pains on all fronts. I praise the core Marionette devs for providing what they do on what, from my knowledge, are much more constrained timelines and budgets.

So with that, what are you looking to know? Perhaps I can be of help. ryan.klose@gmail.com

**Comment by scott-w** [comment]
Hi guys, thanks for your feedback on this, and thanks for the help @ryan-farmer.

Marionette 3 is currently in pre-release and, though we're getting close to having a stable release ready, I have to admit that the documentation is still not where we need it to be.

@curzonj It would be great if you could help us with this effort. We have a number of pull requests and issues open at https://github.com/marionettejs/backbone.marionette/labels/docs. If you could give some targeted feedback on the particular areas that you find lacking - where the docs don't match the code, where there are conflicts, etc. that would fantastic.

**Comment by curzonj** [comment]
@scott-w mostly I was just wishing that the pre-release docs had a warning that they incomplete and/or inaccurate. I totally understand the additional effort required to write docs after the actual code is done.

I added the biggest issue I could remember here https://github.com/marionettejs/backbone.marionette/issues/2959#issuecomment-217640377

**Comment by curzonj** [comment]
@ryan-farmer thank you for the offer. I'll definitely join the gitter. The 2.4.5 docs seem solid so I think I'll use that for now to learn marrionette.

**Comment by curzonj** [comment]
@ryan-farmer I saw this comment in the gitter and changed my `onShow` method to `onRender` and it worked, so I'm on 3.0.0 now :)

```
Sean Anderson @MeoMix May 06 15:26
beforeShow doesn't exist in mn3
show is toast, too
it's all about that render/attach life
```

**Comment by scott-w** [comment]
Thanks for this, that's definitely a worthwhile idea as we have at least one more pre-release to put out.

**Comment by paulfalgout** [comment]
Ok solution is merged, just needs a release now.
