### ISSUE TITLE
Should we use ES6 classes internally

### ISSUE THREAD

**Issue by paulfalgout** [marionettejs/backbone.marionette#3090]
https://github.com/marionettejs/backbone.marionette/pull/2925

This PR opened the discussion essentially.  However since we're mostly extending Bb "classes" I'm not sure we should introduce something different in a couple of cases.  Plus it adds to the transpilation complexities.  But that said it doesn't seem like that big of a deal to switch to it.

Can anyone argue one way or the other?

**Comment by JSteunou** [comment]
If we do not **need** classes I do not see why we should switch to it.

**Comment by scott-w** [comment]
Personally speaking, I'm not sure what we gain from it. Backbone currently provides an implementation for extending classes that seems to work and, from what I've seen, there's nothing in our current implementation that prevents developers utilising ES6 classes themselves.

**Comment by rafde** [comment]
I think I remember reading that classes was causing backbone problems, which instigated having to include a pre-initialize.
Also, all classes do is provide syntactic sugar. And this project may be mostly written using ES6/2015 but it doesn't mean it'll be used in ES6/2015 projects.

Most would just want to use ES6/2015 just because they can, not have to.

**Comment by paulfalgout** [comment]
Sounds good.  👎 to ES6 classes for now then.
