### ISSUE TITLE
LayoutView documentation notes that region naming issues will be fixed by v2

### ISSUE THREAD

**Issue by bfrost2893** [marionettejs/backbone.marionette#3116]
In `docs/marionette.layoutview.md` under Region Naming, it discusses conflicts with specific Region Names. Has this been fixed? If it hasn't, this doc should be updated to specify when it might be fixed next. If it's been fixed, it might be okay to remove this section from the docs. 

https://github.com/marionettejs/backbone.marionette/blob/master/docs/marionette.layoutview.md#region-naming

**Comment by paulfalgout** [comment]
It is fixed in `v3` which is awaiting release.  But it is not fixed in `v2` and cannot be fixed.  Fixing it is a breaking change which requires a version bump.  Actually this is less of something that needed to be fixed and more of a known caveat of a feature.  That said, that feature was removed in v3 and `getRegion` is the preferred way to access a region if you can't just use `showChildView`
