### ISSUE TITLE
Document View element removal

### ISSUE THREAD

**Issue by scott-w** [marionettejs/backbone.marionette#3172]
Reported by @bazineta

~~In Mn 3, a DOM element is removed from the DOM tree before any events fire on its children. For example:~~

``` javascript
import {View} from 'backbone.marionette';

const SecondChild = View.extend({
  onBeforeDestroy() {
    console.log('This is already out the DOM');
  }
});

const FirstChild = View.extend({
  regions: {
    child: '.child-hook'
  },

  onRender() {
    this.showChildView('child', new SecondChild());
  }
});

const Root = View.extend({
  regions: {
    child: '.child-hook'
  },

  onRender() {
    this.showChildView('child', new FirstChild());
  }
});

app.getRegion().show(new Root()); // Renders everything

app.getRegion().empty();
```

In this example, by the time, the log hits, `SecondChild` is no longer visible in the DOM tree.

**Comment by bazineta** [comment]
For our application, this isn't a documentation issue; rather, it's a showstopper.

Consider the case where SecondChild is using a plugin of some type, that provides a 'destroy' function. Examples; Bootstrap's Carousel widget, which must be paused before being removed from the DOM, Highcharts, which will leak without being destroyed, innumerable jQuery and Bootstrap plugins.

In 2.x, one could use 'onBeforeDestroy' for this purpose -- the plugin could then be torn down as the view was going away.

In 3.x, this isn't possible; the chances of a view not being in a hierarchy of views is practically zero, and thus by the time any of the view destruction lifecycle events are called on it, it's no longer in the DOM tree, and 'destroy' functions are going to likely be at best entertaining; for example, the Bootstrap Carousel widget actually re-instantiates itself, which is a bit ironic considering that we were trying to prevent leaks, not make more of them.

As it stands, the destruction lifecycle events seem to be of questionable value, if by the time the lifecycle event fires, the view is in a zombified state; by the time any lifecycle event fires, a leak has already occurred and nothing can be done about it. Other than completely reinventing destruction lifecycle via some type of pre-destruction notification all the way down an arbitrary nesting hierarchy, there seems no way in 3.x to prevent leaks.

**Comment by bazineta** [comment]
As an example of the view destruction lifecycle events being odd in this situation, consider that for SecondChild, any onBeforeDetach event fires, from its perspective, after it's been detached. That will actually have occurred when Root was destroyed; both children however will receive a 'before:detach' event after the fact.

**Comment by paulfalgout** [comment]
As far as I can tell  detach seems to be propagating correctly.  The detach events should traverse the children so that things can be removed appropriately.  I would not recommend destroy for plugin type stuff..  Anything DOM related should use  `attach` `detach` and `onDomRefresh` events which are ideal for plugins.   destroy is better for listeners or non-dom related things that keep the full lifecycle of the view.

Is there a situation in which detach on children is not working?
https://jsfiddle.net/fLv382y7/5/

The original change was made with a flag in v2 https://github.com/marionettejs/backbone.marionette/pull/2141

The flag was defaulted to the v2 behavior, but in v3 the old behavior was removed.  This makes both the View and CollectionView follow the same rules for destroying their children...

In the meantime if necessary inside a View's `onBeforeDestroy` you can destroy the children as needed..  in a View `this.removeRegions()` would do it.. in CollectionView `destroyChildren` was made private.. so.. that one is less straight forward.

But again hopefully this isn't necessary.

**Comment by bazineta** [comment]
Sure, the detach event is propagating correctly, but it's by then old news; using our example above, SecondChild and FirstChild are subviews of Root.  In the View mixin destroy(), we have this at present:

```
  // remove the view from the DOM
      // https://github.com/jashkenas/backbone/blob/1.2.3/backbone.js#L1235

      this._removeElement();

      if (shouldTriggerDetach) {
        this._isAttached = false;
        this.triggerMethod('detach', this);
      }

      // remove children after the remove to prevent extra paints
      this._removeChildren();
```

Unless I'm just not getting this, then due to the this._removeElement(), any 'before:detach' events in the subviews aren't really true; the entire tree has been smoked in the top-level view. If any of the subviews actually had things that were DOM-related that needed to be handled in onBeforeDetach(), it's too late now.

**Comment by paulfalgout** [comment]
When the detach method is triggered, the view monitor walks the view tree and triggers the event. This happens prior to removeElement. It is handled externally because it also supports backbone views.

**Comment by bazineta** [comment]
The the key would be to document that a view monitor must be used, and one can't simply destroy a top-level view. I think by now many of us have things that look like but aren't collection views (dashboards, etc., things that one couldn't do with collection and composite, so you typically rolled your own using babysitter), and in 2.x, calling destroy at the top level worked as expected. That's no longer true, and one must have a view monitor present now, or the behavior will be undesired.

**Comment by paulfalgout** [comment]
I do think this is best handled with docs.  However I also think that parent view's can easily manage non-monitored views in either `before:detach` or `before:destroy` by detaching or destroying non-managed children.  Though I would recommend using `Region`s or `CollectionView`s everywhere. I would personally avoid any other view management, or in the very least utilize `Marionette.monitorViewEvents` directly for self-managed views.

In any case, introducing the detach events are a better way of handling the DOM management that was previously impossible in certain edge cases such as `preventDestroy` in which a view may have been detached, but _no_ event was thrown indicating the view was no longer in the DOM.

Plus the `before:destroy` and `destroy` events were pretty much exactly the same event and had no real differentiating purpose.  They were both essential `before:destroy` events and they doubled as `detach` events, even if it was never _really_ true.  For instance if you had to cleanup in a `destroy` for a plugin, you possibly had to check first for its existence because if the view was rendered but never attached, it may never have been added in the first place.

Perhaps worse though is that parent views could not previously manage anything on children in `onBeforeDestroy` as they were already gone by that time.

Additionally when mixing `LayoutView`s and `CollectionView`s there were multiple issues of double renders or missing attach events on grandchildren that have been solved in v3.

**In v2**
https://jsfiddle.net/fLv382y7/8/

(index) | name | event | isAttached
------ | ---- | ----- | ---------
0 |	"Root" |	"before:attach" |	false
1 |	"FirstChild" |	"before:attach" |	false
2 |	"SecondChild" |	"before:attach" |	false
3 |	"Root" |	"attach" |	true
4 |	"FirstChild" |	"attach" |	true
5 |	"SecondChild" |	"attach" |	true
6 |	"SecondChild" |	"before:destroy" |	true
7 |	"SecondChild" |	"destroy" |	true
8 |	"FirstChild" |	"before:destroy" |	true
9 |	"FirstChild" |	"destroy" |	true
10 |	"Root" |	"before:destroy" |	true
11 |	"Root" |	"destroy" |	true



**In v3**
https://jsfiddle.net/fLv382y7/9/

(index) | name | event | isAttached
------ | ---- | ----- | ---------
0 |	"Root" |	"before:attach" |	false
1 |	"FirstChild" |	"before:attach" |	false
2 |	"SecondChild" |	"before:attach" |	false
3 |	"Root" |	"attach" |	true
4 |	"FirstChild" |	"attach" |	true
5 |	"SecondChild" |	"attach" |	true
6 |	"Root" |	"before:destroy" |	true
7 |	"Root" |	"before:detach" |	true
8 |	"FirstChild" |	"before:detach" |	true
9 |	"SecondChild" |	"before:detach" |	true
10 |	"Root" |	"detach" |	false
11 |	"FirstChild" |	"detach" |	false
12 |	"SecondChild" |	"detach" |	false
13 |	"FirstChild" |	"before:destroy" |	false
14 |	"SecondChild" |	"before:destroy" |	false
15 |	"SecondChild" |	"destroy"	 |false
16 |	"FirstChild" |	"destroy" |	false
17 |	"Root" |	"destroy"	 |false

**Comment by bazineta** [comment]
So to close this out for posterity, the original problem that caused this discussion was that rolling one's own container View subclass to manage subviews is required from time to time. In our case, most critically, a drag-and-drop dashboard. The only thing that this shares with a CollectionView is the concept that it manages subviews. Using regions for this purpose isn't a viable solution, so the view needs to manage the subviews in another way.

In 2.x, we handled that via a View subclass, using a babysitter to manage the subviews. 3.x changes things around quite a bit in this respect, and a naive port will lead to anguish.

For that use case, given the discussion above and experimentation this morning, one solution appears to be as follows:

Extend from View.
Implement _getImmediateChildren
Implement _removeChildren
When adding a view to the container view, call Marionette.monitorViewEvents(view).

Is that correct?

**Comment by paulfalgout** [comment]
I think that'd do it, but as a side-note, I am very interested to know more about the implementation of the drag-drop dashboard. I'm wondering what might have to change about CollectionView or View to support it.

**Comment by bazineta** [comment]
Fair enough; I'll try to distill it down to something simple.

**Comment by scott-w** [comment]
@paulfalgout @bazineta Do you guys consider this issue closed now?

**Comment by bazineta** [comment]
I still owe @paulfalgout a drag and drop demo. That's been delayed by that whole day job thing, but I still think it'd be generally beneficial, so if we could hold this open for a short time, that'd be great.

**Comment by scott-w** [comment]
No worries 👍

**Comment by paulfalgout** [comment]
> Extend from View.
> Implement _getImmediateChildren
> Implement _removeChildren
> When adding a view to the container view, call Marionette.monitorViewEvents(view).

So with this.. 3 thoughts..

1. We could make public `_getImmediateChildren` and `_removeChildren` for this purpose.
2. We could make a Marionette.Babysitter library that is simple Backbone.Babysitter but with the private stuff implemented.
3. No change.  Implement babysitter at your own risk.

#2 is a tiny bit harder and means more maintenance, but less things get publicized... seems like it wouldn't be hard to maintain.. but I dunno.

**Comment by paulfalgout** [comment]
@marionettejs/marionette-core 
After working on `NextCollectionView` I'm kind of falling on the side of #1.  We can just make these functions public and document them along with `monitorViewEvents` We should just document them in the code maybe that they're not for calling directly.. 

Although @bazineta I do think `NextCollectionView` might be enough to handle any custom use-case.

**Comment by paulfalgout** [comment]
closing as part of current work
