### ISSUE TITLE
Backbone.Babysitter replacement missing .call and .apply

### ISSUE THREAD

**Issue by jgkinnear** [marionettejs/backbone.marionette#3203]
### Description
The replacement for Backbone.Babysitter (Container) doesn't have .call and .apply methods. The Container could have those methods added back in, or the upgrade guide detail the breaking change.

Means the following is no longer available
`view.children.call('doSometing')`

### Expected behavior
I would like the methods added back in purely for compatibility

### Environment

1. Marionette version: 3.0.0
2. Backbone version: 1.3.3

**Comment by paulfalgout** [comment]
Definitely need to document the breaking change, even if we revert it.

However `call` is redundant.  `view.children.invoke('something');` is the same, but a better API handled by underscore.. now in lodash I believe `invoke` is now `invokeMap`..  so if we want to fully support that we should probably add it.. however `myBackboneCollection.invokeMap('something)` isn't going to work either, so I dunno..
`apply` is a little less convienent.  perhaps not with ES6 spread.. but otherwise it'd be something like `view.children.invoke.apply(view.children, ['something].concat(arguments));`

@marionettejs/marionette-core ?

Xref: https://github.com/marionettejs/backbone.babysitter/issues/57

**Comment by rafde** [comment]
to be fair, that issue in the ref link hasn't been closed because it hasn't happened there yet. So the removal of `call` and `apply` did come out of nowhere without deprecation warning (despite their redundancy.

What would be fair is announcing their deprecation and remove for V4 in favor or `invoke` or whatever.

**Comment by paulfalgout** [comment]
This is one among many changes in v3 that were not deprecated ahead of time. The babysitter library was and will likely continue to be woefully unmaintained. If we want to walk this one back that's fine, but it could be one among many. v3 was too large, too long, and with too little contribution. I'd lean towards documenting and not repeating the mistakes of v3 rather trying to resolve them fully.

**Comment by jgkinnear** [comment]
I dont think its necessary to walk back, considering there are alternatives like 'invoke' that are available. The Container specifically would be made publicly accessible too...

`Marionette.Container = Container;`

**Comment by paulfalgout** [comment]
The container was purposefully made not accessible so that `CollectionView` can be updated without concern for creating new dependencies on the container itself.

babysitter can be added separately to a project for handling use-cases that would need `Marionette.Container`
