### ISSUE TITLE
CollectionView "filter" not respected when adding/removing models from collection 

### ISSUE THREAD

**Issue by ltoledozt** [marionettejs/backbone.marionette#3274]
### Description:

The 'filter' method allow 3 parameters: model, index and collection.
The issue is in the index parameter.

I created a sample to reproduce the issue:
There's a button where the user can add new elements in a collection. but there's a rule that the view should render just 1 element of this collection.
Regardless of how many elements are in the collection, just one element should be rendered.

When the 'model' parameter is used, the logic works fine. But with the 'index' parameter the method doesn't have the behavior that I expect.
The 'index' is being iterated for all element of the collection. When the iteration ends, the filter is executed again with index equals '-1'.

Demo: http://codepen.io/anon/pen/jVYYjM

### Expected behavior:
 
When the user click the "Add" button, a new element should be added, but the HTML page should render just 1 element.

### Actual behavior:

All the elements of the collection are shown in the HTML page.

### Environment

Marionette version: v2.4.7
Note: This issue also happen in the v3.1.0

**Comment by paulfalgout** [comment]
Both `filter` and `sort` were never implemented well enough to handle edge-cases.  And attempting to solve the issues that arise have led to just pushing the bug down the hill.

In v3.2 we will be introducing a [New Restructured CollectionView](https://github.com/marionettejs/backbone.marionette/pull/3244) that should resolve many if not all of the issues that have come up with the current issue.. it will also be magnitudes faster.

I know this isn't super useful in your current situation as you're still running 2.x and 3.2 isn't out yet.  For your use-case I might suggest the easiest solution might be able to do something like http://www.scottwalton.codes/marionette.collectionhelper/ where you are filtering a collection itself instead of using the `CollectionView` API.

That said, if there is a way that you could try out the new version with a real world scenario: https://rawgit.com/paulfalgout/backbone.marionette/feature/new-collection-view-build/lib/backbone.marionette.min.js is a build including `NextCollectionView`.
