### ISSUE TITLE
Get rid of strange named function expression

### ISSUE THREAD

**Issue by denar90** [marionettejs/backbone.marionette#3284]
After upgrading all dependancies and node version to v6, in build we have strange named function expression [triggerMethod$$](https://github.com/marionettejs/backbone.marionette/blob/master/lib/backbone.marionette.js#L1088). 
Someone pointed on that in chat but we haven't crated issue for it.

**Comment by blikblum** [comment]
Afaik this is the way used by rollup to avoid name clash of variables with same name from different modules.

**Comment by paulfalgout** [comment]
Yep this is rollup.  It might be a bug in rollup, but I'm not certain.  It didn't used to happen, but I'm quite sure it is because there is a function globally scoped to the library with the same name.  It's odd, but it may not be reasonably avoidable.

**Comment by paulfalgout** [comment]
So I think until rollup solves this, we're off the hook here.  I also don't know that it's really an issue.

**Comment by blikblum** [comment]
I've found why this occur:

The ViewMixin `triggerMethod` method creates a named function `triggerMethod` that is in the same scope as the imported `triggerMethod`. So to avoid the conflict Rollup renames it.

If the ViewMixin `triggerMethod` is declared as below the triggerMethod name is preserved

 ```
/* eslint-disable */
triggerMethod: function triggerMethodFn() {
//...
}
/* eslint-enable */
```

I also tested with most recent rollup. It still rename the functions but instead of renaming the imported `triggerMethod` function it renames the ViewMixin method, but unfortunately is not compatible to Mn because of how moduleName is resolved, i.e., 'Marionette = global[\'Mn\']' will not work

**Comment by paulfalgout** [comment]
To prevent having to rename the classes in the `NextCollectionView` I reused the same export names for the classes.  This means the build contains new `$` vars https://github.com/marionettejs/backbone.marionette/blob/master/lib/backbone.marionette.js#L3068

Also this latest build changed to `triggerMethod$1` instead of $$ which to me seems more clear as to what is going on..  particularly since all of the `ClassOptions` do the same.  I don't suspect we'll be fixing the `ClassOptions` numbering.. so I wonder if maybe this is a non-issue?

**Comment by blikblum** [comment]
It's just a cosmetic issue that eventually will be fixed so have no hard opinion about keeping open or not
BTW `ClassOptions` is easiest to fix
