### ISSUE TITLE
No event triggered when pre-generated content is shown?

### ISSUE THREAD

**Issue by jonas-db** [marionettejs/backbone.marionette#3286]
From the documentation it seems that _none_ of the events are triggered when the element is already in the the DOM (e.g. generated HTML from server), or am I wrong? Is there any way to have an event triggered in this case? A potential use case I have in mind is that for example jQuery needs to initialize/register something which would usually occur in the render event.

http://marionettejs.com/docs/master/viewlifecycle.html#views-associated-with-previously-rendered-or-attached-dom

**Comment by paulfalgout** [comment]
This was my suggestion: https://github.com/marionettejs/backbone.marionette/issues/3243

I would be against triggering render or attach since those things have already occurred.. and simply triggering them seem like a hack to get around the actual issue that there is no event.

In the meantime this can be handled however inside the `initialize` by checking `isRendered()`

**Comment by jonas-db** [comment]
I see, I will close this in favour of that one.

**Comment by paulfalgout** [comment]
ping @marionettejs/marionette-core
