### ISSUE TITLE
Using a function for ``template`` in childViewOptions results in model attributes missing from templateContext

### ISSUE THREAD

**Issue by mattaustin** [marionettejs/backbone.marionette#3317]
### Description

When setting ``template`` to a function in a CollectionView's ``childViewOptions``, the model attributes are not available in the template.

### Expected behaviour

This should behave the same way that setting ``template`` on the view does, and model attributes should be available in the template.

### Actual behaviour

Example:
https://jsfiddle.net/mattaustin/qgddxaLx/

Here we have an ``ItemView`` (which can also be used by itself to render a single model without a collection).
The ``CollectionView`` ``childViewOptions`` sets a different template. However the 'title' attribute of the model is unavailable in the template, and results in a underscore error (see browser console). Setting template to be a property (and not a function) results in expected behaviour.

### Environment

1. Marionette version: 3.1.0
2. Backbone version: 1.3.3
3. Additional build tools, etc: Underscore 1.8.3

**Comment by paulfalgout** [comment]
A template is just a function that takes data and returns a string.  There's no way to do `if(this.template typeOf Template)` because a template can be as simple as:
```js
const validTemplate = function(data) {
  return `My template ${ data.foo }`;
}
```
So you can't pass a function and expect it to know that it isn't a template, but is returning a template.  So views have `getTemplate` for overriding.

In your case you have two options.. put a `getTemplate` on your childview so that it can do the logic you're wanting to pass to the `childViewOptions`, or make your template function work like a template.

```js
const CollectionView = Marionette.CollectionView.extend({

  childView: ItemView,

  childViewOptions: {
    tagName: 'li',
    template: function (data) {
      const template =  Marionette.TemplateCache.get('script[type="x-template/underscore"][data-name~="fooListItem"]');
      return template(data);
    }
  },

  tagName: 'ol'

});
```
