### ISSUE TITLE
How do I know when all of my children is in the DOM

### ISSUE THREAD

**Issue by doodlemeat** [marionettejs/backbone.marionette#3321]
I got a CollectionView that needs to know if all its children has been rendered **AND is in the DOM.**

I know the View has onDomRefresh, but there is no such thing for CollectionView. Why is that so?

I can bypass the problem by just putting a setTimeout in onRenderChildren.

**Comment by scott-w** [comment]
The `CollectionView` should have an `onAttach` event that fires on the initial attach. Does that cover your use case?

**Comment by paulfalgout** [comment]
I don't understand how adding a `setTimeout` to `onRenderChildren` is useful.  If you make a fiddle of the use-case I'm sure there's a better way to do what you're asking.. but since the children for a collectionview can change, and because they can maintain themselves, it's difficult to know when _all_ of them are necessarily attached or not for a purely generic solution.

**Comment by doodlemeat** [comment]
Well, I need it for every render ()

**Comment by capricube** [comment]
by default a Marionette collection renders all views into a buffer and only after each child view has rendered attached the buffer to the DOM of the collection view. See http://marionettejs.com/docs/master/marionette.collectionview.html#collectionviews-render.

**Comment by doodlemeat** [comment]
@paulfalgout The reason I used setTimeout is because it worked. I would really go for another approach, but since what I have to do requires all children to be in the DOM after a .render() on the parent collection, I am forced to that ugly solution.

**Comment by paulfalgout** [comment]
I guess what I'm not following... if a `setTimeout` works everytime.. then you should just use `onAttach` on the CollectionView.. however `onAttach` tells you nothing about what happens with the children after the `CollectionView` itself is attached to the DOM.. but then neither does `onRenderChildren` unless you do a full render.  If you _always_ do a full render and that is the only use-case then you need to:
```js
onRenderChildren: function() {
  //setTimeout(this.doFoo);
  if(this.isAttached()) this.doFoo();
},
onAttach: function() {
  this.doFoo();
}
```

**Comment by doodlemeat** [comment]
Actually onRenderChildren will be called after adding a model. Because that is how the CollectionView works. But yea, what I really want to do is listen on all childrens attach event, and when every child has reported theirs attach event, THEN I want to be able to do something with the DOM.

**Comment by paulfalgout** [comment]
> Actually onRenderChildren will be called after adding a model.
Well that's _not_ really true, but if it's true for your use-case, and that's enough, then great.  This is particularly why a code sample would be helpful.


The only time `onRenderChildren` should be called when the children are not attached is before the CollectionView itself is attached.  That's why the `isAttached` check is necessary..  So the first `onAttach` would cover the initial `onRenderChildren` that happens prior to the children attaching.

**Comment by doodlemeat** [comment]
This does not make me any smarter. I am not talking about what happens first, when the views are created and initialized, but the lifecycle. 
If I have the .isAttached() check if onRenderChildren, it will never be true, just tested it.

**Comment by paulfalgout** [comment]
Ok... well...

Here's a fiddle proving my suggestions:
https://jsfiddle.net/x3zymq1m/


This fiddle uses `isAttached` inside `onRenderChildren`

Here's what get's logged in the console:
```
onRenderChildren: Children in DOM false
onRenderChildren: CollectionView in DOM false
onAttach: Children in DOM true
Shown in region.
onRenderChildren: Children in DOM true
onRenderChildren: CollectionView in DOM true
```

Again.. if you make a fiddle of your usecase I'm sure we can help determine what the issue is.  Otherwise we'll just be guessing and you'll be left to make false assumptions.
