### ISSUE TITLE
View's this.ui properties are strings during onDestroy event

### ISSUE THREAD

**Issue by rally25rs** [marionettejs/backbone.marionette#3326]
### Description

I have a view that renders a child view in a region using `.showChildView('myregion', new MyView())`

The `MyView` view contains:

```
module.exports = Backbone.Marionette.View.extend({
  template: template,

  ui: {
    expressionSelect: 'select[name="expressions"]'
  },

  onRender() {
    this.ui.expressionSelect.chosen();
  },

  onDestroy() {
    this.ui.expressionSelect.chosen('destroy');
  },
```

This is just trying to set up and destroy the `chosen` jQuery plugin on an element.

The problem is that during `onRender`, `this.ui.expressionSelect` is a jQuery element, as expected.
During `onDestroy`, `this.ui.expressionSelect` is the string selector.

This kind of occasional "this.ui is strings, not elements" problem has been around for at least 2 1/2 yrs in various Marionette versions.

### Expected behavior

`this.ui` should always be jQuery elements.

### Actual behavior

`this.ui` is sometimes strings during various events or places in the view lifecycle.

### Environment

1. Marionette version: 3.2.0 (though I've seen similar behavior since 2.2.0)
2. Backbone version: 1.3.3
3. Additional build tools, etc:

**Comment by rally25rs** [comment]
It seems that maybe I really want to be using `onBeforeDestroy`?
The `this.ui` properties are still correct during that event.

During `onDestroy` the elements are still part of the view and doing `this.$el.find(this.ui.whatever)` can still get the elements. It would make sense to reset the `this.ui` properties back to strings if the elements were destroyed, but they have not been yet.

**Comment by paulfalgout** [comment]
Yes `onBeforeDestroy` is best for clean up (or onBeforeDetach if the view needs to be in the DOM).  `onDestroy` is _after_ destroy has occurred.. so really there's very little use for `onDestroy` beyond being consistent with event naming.

For the most part, since a destroyed view cannot be reused, the clean up work is whatever is minimally necessary to prevent leaking and isn't attempting to return the view to any particular state.  However destroy calls [`unbindUIElements`](https://github.com/marionettejs/backbone.marionette/blob/master/src/mixins/ui.js#L97) which returns the `ui` hash to it's previous state.. that's more so for other users of `unbindUIElements` than for destroy.

**Comment by rally25rs** [comment]
Thanks for the clarification. This project was a migration from v2 and I thought `this.ui` held the context back in that version. I could be wrong though. Renaming all my `onDestroy` functions to `onBeforeDestroy` will just be a note I add to my project migration checklist.
Thanks again!

**Comment by paulfalgout** [comment]
That is true.. in v2.x `onDestroy` was called before most of the view was destroyed or even removed from the DOM.  I think the though was that it would be more useful, although incorrect.  I believe it was needed because of the way inheritance was working `onBeforeDestroy` wasn't useful in some cases..  anyhow.. now it's consistently at the end of the action like all the other events.

Instead of: https://github.com/marionettejs/backbone.marionette/blob/v2.4.7/src/view.js#L163

**Comment by rally25rs** [comment]
Might be worth adding to the upgrade guide http://marionettejs.com/docs/v3.0.0/upgrade.html
