### ISSUE TITLE
childViewEventPrefix is confusing... way to change it between multiple child views?

### ISSUE THREAD

**Issue by rally25rs** [marionettejs/backbone.marionette#3353]
### Description

This is more of a design question than an issue...
I'm trying to figure out how to use the child view event bubbling correctly when a view has more than 1 child view.

Say for example something like:

```
const ParentView = Marionette.View.extend({
  regions: {
    leftPanel: '.left',
    rightPanel: '.right'
  },

  onRender() {
    this.showChildView('leftPanel', new PanelView({...});
    this.showChildView('rightPanel', new PanelView({...});
  }
});
```

So I have 2 of the same `PanelView` (though it doesn't really matter if they are the same type).
If either of those PanelViews can trigger a `change` event, how do I know which threw it?

### Expected behavior

The way I originally _thought_ `childViewEventPrefix` would work (which it does not) would be:

```
const ParentView = Marionette.View.extend({
  regions: {
    leftPanel: '.left',
    rightPanel: '.right'
  },

  onRender() {
    this.showChildView('leftPanel', new PanelView({
      childViewEventPrefix: 'left'
    });

    this.showChildView('rightPanel', new PanelView({
      childViewEventPrefix: 'right'
    });
  },

  onLeftChange() { ... },

  onRightChange() { ... }
});
```

### Actual behavior

What really happens is that the `childViewEventPrefix` of the "parent" view receiving events is used, so all child views are always prefixed with the same value.

From some debugging it seems like ParentView receives 'change' from a child view then re-triggers `${this.childViewEventPrefix}:change` on itself, where `this` is the parent view (event receiver, not event sender).

### The actual question

What is the "correct" way to set up implicit handlers for multiple child views?

I'd like to avoid having to `this.listenTo(` each child view explicitly.

My temporary workaround has been to add an `eventPrefix` parameter to my `PanelView`'s options and have it prefix it's own `change` event with that, but then the implicit event handlers are:

```
onChildviewLeftChange() {...},
onChildviewRightChange() {...}
```

### Environment

1. Marionette version: 3.2.0

**Comment by paulfalgout** [comment]
A related issue has been brought up before: https://github.com/marionettejs/backbone.marionette/issues/2783

My personal belief is that we should avoid adding any additional complexity to child event proxying.
I also think `childViewEventPrefix` should be used sparingly and am hoping to disable it by default at some point.  `childViewTriggers` is a better interface. It prevents unnecessary event bubbling and creates an explicit configuration so that it more reasonable to understand when a particular event is no longer being listened to when refactoring.  I do think there are use-cases, when creating very generic components, for `childViewEventPrefix`, otherwise I wouldn't use it.

The original design of `childViewEventPrefix` was for `CollectionView`.  It was later added to the View.  In _both_ cases it may make sense to partition child events, but doing so would add complexity to every event, listened to or not.

A better solution as mentioned on the other issue is either triggering the view or some other identifier to the handler, or something like this: https://jsfiddle.net/g9znf174/

It is possible this could be looked at again if we ever do https://github.com/marionettejs/backbone.marionette/issues/2508

Certainly open to other ideas though.
