### ISSUE TITLE
compiled code of Array Destructuring Assignment  could not run on IE 9-

### ISSUE THREAD

**Issue by JounQin** [marionettejs/backbone.marionette#3354]
### Description

There are some destructuring assignment in source code, and it finally compiled into some codes which are not supported on IE 9- (`Array.isArray`, `Array.from`)
 
https://github.com/marionettejs/backbone.marionette/blob/master/src/mixins/behaviors.js#L61,L89

https://github.com/marionettejs/backbone.marionette/blob/master/lib/backbone.marionette.js#L700

### Expected behavior

do not use array destructuring assignment in source code.

### Actual behavior
should run well on IE9- also

### Environment

1. Marionette version: 3.2.0
2. Backbone version: 1.3.3
3. Additional build tools, etc: it is babel's wrong?

**Comment by scott-w** [comment]
Good find @JounQin 

@marionettejs/marionette-core On the similar subject, have we documented the versions of IE that we support?

**Comment by paulfalgout** [comment]
I believe ie9+ is documented on the readme. Can check later. This issue is not about destructuring. We should be able to transpile for ie9.

**Comment by paulfalgout** [comment]
Nope just the saucelabs stuff, but that starts at IE10.  Honestly though I think that's a reasonable expectation.  IE9 support ended even for extended support April 11th 2017.  There will be no more security updates for that browser.  While this _is_ a problem for browsers we support.. I don't know that we should actively be concerned with IE9 and below.  To support those browsers we should require polyfills.

While we do destructuring all over the place.. it's only the 3 behavior instances that are causing the issue.  I think because we include the babel-polyfill in the test runner we're not seeing IE11 fail.. so I'm going to break it first.. then try to fix it.

**Comment by paulfalgout** [comment]
Ok.. so _again_ further inspection #3355 does remove the `_toConsumableArray` issue.  However.. this problem is _only_ for IE8 and below as `Array.isArray` works in IE9, _and_ what we're passing to `_toConsumableArray` is _always_ an array and these are all private functions so `Array.from` will _never_ be an issue.

While I don't particularly care to support IE9.. I _really_ don't care to support IE8.  IE8 can polyfill `Array.isArray`
```js
if (!Array.isArray) {
  Array.isArray = function(arg) {
    return Object.prototype.toString.call(arg) === '[object Array]';
  };
}
```
That said I'm ok with this either way.  There's some useful test fixing in #3355 that we will want.. But our lib currently supports IE9+ with no issues.  I'm ok with putting the destructuring back in, or we can keep the changes..  @marionettejs/marionette-core thoughts?

**Comment by JSteunou** [comment]
I only support IE11+ for Microsoft, so I always advice to add shim for IE for those really in need of old IE support.
