### ISSUE TITLE
Getting rid of jQuery

### ISSUE THREAD

**Issue by PhilippMi** [marionettejs/backbone.marionette#3380]
### Description

I tried to remove jquery from my project by following the instructions in [DOM Mixin API](https://github.com/marionettejs/backbone.marionette/blob/v3.3.1/docs/dom.mixin.md). However, I did not succeed.

Firstly, Marionette uses other Backbone functions which depend on jQuery than the 3 mentioned in [DOM Mixin API](https://github.com/marionettejs/backbone.marionette/blob/v3.3.1/docs/dom.mixin.md#backbone-jquery-integration) like [setElement](https://github.com/marionettejs/backbone.marionette/blob/v3.3.1/src/view.js#L95) and [delegateEvents](https://github.com/marionettejs/backbone.marionette/blob/v3.3.1/src/mixins/view.js#L68). So if you want to get rid of jQuery you need to override these methods too.

So, I tried to use [Backbone.NativeView](https://github.com/akre54/Backbone.NativeView) to handle these methods for me. However, Marionette is not working with NativeView. One of the issues I encountered was that Marionette expects `setElement` to set `this.$el`. Another issue was that triggers did no longer work.

So, my question is: Has anybody tried get rid of the jQuery dependency and succeeded? Or is the DOM Mixin API just a first step and was not meant to work at the current state of the project?

### Environment

1. Marionette version: 3.3.1
2. Backbone version: 1.3.3
3. Backbone.NativeView version: 0.3.3

**Comment by blikblum** [comment]
Yes It is possible but not in a straight way. There are a lot of caveats.

I Will publish somewhere my findings about the subject soon.

**Comment by loriensleafs** [comment]
I've also struggled a lot with this.  The problem with a lot of examples is they're not in the context of a bundler like Webpack, Webpack2, Rollup, etc, which all have their own caveats.

**Comment by rafde** [comment]
https://github.com/marionettejs/backbone.marionette/pull/3372 is in the works, but I think this PR will need test as proof of concept to ensure such a thing is possible. 
When https://github.com/marionettejs/backbone.marionette/blob/v3.3.1/src/view.js#L92 was linked I immediately saw https://github.com/marionettejs/backbone.marionette/blob/v3.3.1/src/view.js#L98 being an issue since that is explicit jQuery usage.

Not sure what bundlers has to do with this issue. Unless it has to do with Backbone requiring jQuery.

**Comment by blikblum** [comment]
I uploaded an implementation at https://github.com/blikblum/js-framework-benchmark/tree/marionette-tests/marionette-native-v3.3.1 
No time to make the notes or run the benchmarks. Will try in the weekend

**Comment by paulfalgout** [comment]
@rafde `setElement` should work with the `this.$el.length` check as even in `backbone.nativeview` `this.$el` will remain array-like using something like `querySelectorAll`
Maybe there's better ways to do it, but honestly something that queries and returns something with `length` seems like a reasonable requirement vs needing to look at the DOM for content

**Comment by blikblum** [comment]
As promised i did the technical notes about using Marionette without jQuery. It can be found at https://github.com/blikblum/js-framework-benchmark/blob/marionette-tests/marionette-native-v3.3.1/marionette-native-notes.md

I also updated the implementation to ditch jQuery completely

**Comment by PhilippMi** [comment]
I only wanted to get rid of jQuery because of the huge size of jQuery (30KB minified/gzipped), but after trying your benchmarks, I found a much better argument: JavaScript performance.
<table>
<tr>
 <th scope="col">Test</th>
 <th scope="col">with jQuery</th>
 <th scope="col">native</th>
</tr>
<tr>
 <td>run</td>
 <td>2196ms</td>
 <td>643ms</td>
</tr>
<tr>
 <td>add</td>
 <td>3414ms</td>
 <td>1071ms</td>
</tr>
<tr>
 <td>update</td>
 <td>222ms</td>
 <td>140ms</td>
</tr>
<tr>
 <td>swap</td>
 <td>925ms</td>
 <td>1105ms</td>
</tr>
<tr>
 <td>clear</td>
 <td>726ms</td>
 <td>386ms</td>
</tr>
</table>

Disclaimer: That was just a quick run of the benchmark and needs more re-runs to be representative.

**Comment by blikblum** [comment]
It's true. Time allowing i will create a blog post about the performance  of different rendering strategies.

If you look at the repository you will find some variants and i will add some more.

**Comment by blikblum** [comment]
BTW to evaluate the performance impact of native you should compare with notrigger variant instead of the base one since it have some optimizations

**Comment by paulfalgout** [comment]
So I think as of v3.4 all of jQuery can be removed from `Marionette`..  however removing it from backbone is a slightly different story and since we extend backbone.view, those would have to be addressed somehow.  That said, I think all of the work remaining in this issue, isn't something the library needs to address directly, outside of perhaps documentation.

**Comment by PhilippMi** [comment]
Here is the Backbone documentation on how to remove jQuery from Backbone: https://github.com/jashkenas/backbone/wiki/using-backbone-without-jquery

It's not that hard to do, all you need is basically [Backbone.NativeView](https://github.com/akre54/Backbone.NativeView) and [Backbone.NativeAjax](https://github.com/akre54/Backbone.NativeAjax).

**Comment by paulfalgout** [comment]
Well the issue is that you can't change the inheritance of Marionette's Views from `Backbone.View` to `Backbone.NativeView`.  So while, yes it is moderately straightforward, people still currently would have to reapply the NativeView changes to `Marionette.View` manually.  There isn't a straight-froward story.

**Comment by blikblum** [comment]
I created a package with the necessary code and instructions to remove jQury dependency: https://github.com/blikblum/marionette.native

**Comment by paulfalgout** [comment]
Looks solved enough for me.  Reopen if problematic
