### ISSUE TITLE
Lodash 5 Support

### ISSUE THREAD

**Issue by rafde** [marionettejs/backbone.marionette#3391]
Jumping the 🔫 but I keep  👀 on https://github.com/lodash/lodash/wiki/Roadmap and noticed that `_.bind` is getting removed in support of `function(){}.bind()`. Before looking further into it, I figure I ask if an effort should be made to remove whatever else is being remove/renamed in Lodash 5 

### Environment

1. Marionette version: 3.x
2. Backbone version: 1.3.3 Will probably hold back official support until it's resolved there.
3. Additional build tools, etc: Lodash 5

**Comment by paulfalgout** [comment]
whew.. that's quite a lot of changes..  hmm..  I wonder if backbone will support lodash 5?

**Comment by rafde** [comment]
Posted an https://github.com/jashkenas/backbone/issues/4145
Will have to submit a PR later. If that gets received well, then this repo is next.

**Comment by bazineta** [comment]
I think at this point _.bind() is no real loss; affects IE8 types only, and by now those folks are used to things being broken. I don't recall any real fallout from this, for example: (https://github.com/NYTimes/backbone.stickit/pull/308)

**Comment by russplaysguitar** [comment]
FWIW, I've given up on trying to use Lodash with Backbone and Marionette. Lodash has diverged enough that it is no longer a drop-in replacement for Underscore. 

I do still use Lodash, but I make sure that Backbone and Marionette import Underscore, while my own code imports Lodash. I admit this is potentially confusing given that the convention is map them both to `_`, but at least I don't have to worry about compatibility issues.

**Comment by paulfalgout** [comment]
Interesting.  I don't use lodash much when using marionette either, but all of the tests are run against v4 of lodash, so other than the proxied functionality everything should work without issue.  Though I can't necessarily speak for backbone itself..  Do you have any further details as to particular pain points?    This does seem to be _somewhat_ of a lesser issue now with tree-shaking anyone can pull in parts of lodash that aren't in underscore, but it'd still be nice to publicly be able to not require `underscore`

**Comment by russplaysguitar** [comment]
I first noticed problems when I tried to upgrade Lodash 4 from v3. From what I recall, the biggest issue was that `invoke` was renamed to `invokeMap`. That change broke code which called `collection.invoke()` since it is a Backbone-created proxy from `collection.invoke()` to `_.invoke()`. I think some other proxy methods were broken as well, like `collection.contains()` and `collection.where()`. 

I started writing a shim to fix those issues, but then I realized that I was introducing more risk and maintenance overhead than it was worth. Was I willing to maintain my shim as Lodash continued to evolve? And what was the point? Backbone would work the same either way. It's possible I'm missing out on some performance gains in Backbone/Marionette, but that's not really the reason why I'm using Lodash anyways.

**Comment by paulfalgout** [comment]
Ah yep the proxies are definitely an issue in compatibility.. not much to do about that I don't think.  Particularly on the backbone side.  However those proxies are essentially `_.invokeMap(collection.models, ...` === `collection.invoke(...`  But outside of the proxy helper functions, I _think_ lodash is still fully supported, but it's hard to say definitively as I don't know if lodash still tests against the backbone unit tests or not, be try and keep up with it on our end.  But as you're doing I've found `underscore` is good enough and if I need something `lodash` specific I can include just that module (or tree-shake the module I suppose) and it doesn't add much weight overall.
