### ISSUE TITLE
childViewEvents "dom:refresh" and region.currentView is null

### ISSUE THREAD

**Issue by firebird631** [marionettejs/backbone.marionette#3404]
I've just migrate from 2 to 3, and I've an issue with a dom:refresh event into a childViewEvents.

```
childViewEvents: {
    'dom:refresh': function(child) {
        var region = this.getRegion('regioname');
        if (region.currentView) { ... }
    }
}
```

Using v2 region.currentView is defined and valid, but since 3.x the value is null. So I think this value is set after the event, but was before, how to have this information now ?

**Comment by paulfalgout** [comment]
Interesting.  So the `child` would be the view, but that doesn't help because you don't know _which_ view it is?  `child` doesn't help in this instance?


It is definitely happening afterwards.
https://github.com/marionettejs/backbone.marionette/blob/master/src/region.js#L136

Seems like an unintended break.   Other than organization I don't know why it would need to be moved afterwards.  This might be considered a bug.  @marionettejs/marionette-core ?

**Comment by rafde** [comment]
I think it's a bug. Just need to swap [these lines](https://github.com/marionettejs/backbone.marionette/blob/master/src/region.js#L75-L77)?

**Comment by paulfalgout** [comment]
I kinda think it should be:
`before:attach`
`attachHtml`
`this.currentView =`
`attach`

Similarly:
`before:detach`
`detachHtml`
`delete this.currentView;`
`detach`

**Comment by rafde** [comment]
I expect
```js
before:detach
detachHtml;
detach;
delete this.currentView;
```
so that the view is always there.

**Comment by paulfalgout** [comment]
I disagree.  I believe the pattern should be the same.  I would agree that this makes the `detach` event less useful, but it is pretty much by definition less useful.  putting the delete in the middle makes the detach event safe for attaching another child.. which may be the only real use case for this event.  If the delete was after it would be impossible.

**Comment by rafde** [comment]
ok. Would it be good to pass the old view via a param object to the detach event? It deviates from the other events, but this could help parent listeners.

**Comment by paulfalgout** [comment]
The detach current gets passed the view that is detached.  To relate to the original part of the issue.. if you were listening to the `childViewEvents` `detach` the event would receive the detached view as the 1st argument, but the region it was detached from would have no knowledge of the view at that point..

**Comment by paulfalgout** [comment]
Actually I withdraw my original thought here.. whether or not the view is being attached to the DOM or not is somewhat inconsequential.. if the region isn't currently attached to the DOM, the attach events aren't going to occur here anyways..  _so_ it probably makes sense to just set the currentView before attempting to render/attach.. because it's most inconsequential.  We _shouldn't_ remove the currentView after detaching though due to possibly accidental removes if a user attaches a new view on a child's detach... so that can stay how it is.  I also don't think this fix would be breaking
