### ISSUE TITLE
Show an error or warning when view has no el after call to setElement

### ISSUE THREAD

**Issue by blikblum** [marionettejs/backbone.marionette#3451]
### Description

 1. When an non existent selector is passed to view.el, the view gets an undefined `el` and an empty `$el`
 2. Vanilla Backbone and current Marionette does not throw any warning or error

### Expected behavior

To be discussed here: keep as is? Log a warning? Show an error? (The two later only behind DEV_MODE?)

**Comment by paulfalgout** [comment]
I don't have a lot of thoughts here either way.  It's worth noting that in some cases errors will be thrown when trying to use this view.. particularly if you're utilizing a custom DOM API that depends on the `el` instead of `$el`.  

The current case is that most views in this state will essentially do nothing.. which seems potentially worse than an awkwardly thrown error.  I don't know of a use case for a view with an undefined `el`..  It seems like an error is useful as the check is nearly free.  `if (!this.el) error`

**Comment by blikblum** [comment]
For the record, when instantiating a NextCollectionView with a non existing element an crash will occur in `getEmptyRegion`

Here is a test:
```

   describe('when instantiating a NextCollectionView with a non existing DOM element', function() {
      beforeEach(function() {
        this.collectionView = new MyCollectionView({el: '#nonexisting'});
      })
      it('should not be attached', function() {
        expect(this.collectionView.isAttached()).to.be.false;
      });
    });
```

**Comment by paulfalgout** [comment]
Ok.. so we can discuss this if necessary but I'm closing it for the moment as due to possible changes in Region `el` will not be required at instantiation removing the `NCV` error needed.. So while it's unlikely you'd want a view with `el` undefined, until you try and render it or show it or something it's not entirely invalid.
