### ISSUE TITLE
Error caught on show child View in the region

### ISSUE THREAD

**Issue by iegik** [marionettejs/backbone.marionette#3591]
### Description

 1. The `ViewDestroyedError` has been caught, when trying to `.show` new `View` instance in `region`
 2. Attach View instance to the region after initialization.
 3. Trying to show Marionette.View (3.0) in Marionette.LayoutView (2.4) region, but `_ensureViewIsIntact` contains the checking of  `if (this.isDestroyed) ...`, while `isDestroyed` for that moment was a function.
 4. Need to support backword compatibility.

Solution:
```
onRender: function () {
  var view = new Marionette.View({});
  view.isDestroyed = false; // Force isDestroyed value
  this.region.show(view);
}
```

### Expected behavior

No error

### Actual behavior

ViewDestroyedError

### Environment

1. Marionette version: 2.4.7
2. Backbone version: 1.2.3
3. Additional build tools, etc: another Marionette v3.0.0

**Comment by paulfalgout** [comment]
I'm not sure how to proceed here.  The nature of major releases is that there are breaking changes.

Your workaround for making a v3 view show in a v2 region is probably the best that can be done.

**Comment by iegik** [comment]
Possible solution is replace everywhere `if (this.isDestroyed)` to `if (this.isDestroyed === true)`

**Comment by paulfalgout** [comment]
In v3 the only thing that checks for `isDestroyed` is the region itself upon showing.  This is the major point at which it is important to check.  Additionally v3 introduced `isDestroyed()` to solve the very problem you are having.

Sure we could modify v2 to support showing v3 views (is that really backwards compatible?  sounds like forwards compatible?)  but then do we also need to do the opposite and allow showing v2 views in v3 regions?  because if `isDestroyed` is expected to be a function.. uh oh another problem.

The issue here is that major versions implement breaking changes and you'll need to monkey patch them to get them to work together.  If it was compatible it would have been a minor point bump.
