### ISSUE TITLE
filter() called exponentially if view.render() is called before collection.fetch()

### ISSUE THREAD

**Issue by russplaysguitar** [marionettejs/backbone.marionette#3592]
### Description

If a CollectionView `filter` has been defined, it is called an exponential number of times. This is increasingly problematic for large collections (1000+ items). 

### Expected behavior

`filter()` should be called `n` times even if `render()` is called before `fetch()`. 

### Actual behavior

- If `render()` is called before `fetch()`, then`filter()` is called `n^2+2n` times. 
- If `render()` is called after `fetch()`, then `filter()` is only called `n` times. 

CodePen: https://codepen.io/anon/pen/PepbVw?editors=0012

### Environment

1. Marionette version: 3.5.1
2. Backbone version: 1.3.3
3. Additional build tools, etc: N/A

**Comment by russplaysguitar** [comment]
Thanks! I didn't think to check out NCV. I just tried changing it in the codepen and it seemed to work, so this will give me a good excuse to upgrade to Marionette 3.5.1 :)

**Comment by russplaysguitar** [comment]
I finally got around to trying this out, and NextCollectionView (and CollectionView in 4.0) have a different problem when handling a large collection: they render all items in the collection first (in memory), then display the views that match the filter. Rendering 1,000+ views tends to slow down the initial load time. I'm at a loss of where to go from here, any suggestions would be appreciated.

**Comment by paulfalgout** [comment]
The NCV/v4 instantiates all of the view's (since the view instance is what is passed to the viewFilter) but it will only render the views that get attached.  To handle very large collections it might be best to give the collection models in batches to offset the instantiation cost.  However with NCV each child will only _ever_ be rendered a single time, no matter how many times it is filtered in or out, and _only_ at the point that it will be attached.  But you can also look into why instantiation takes a while.  What makes your child costly to instantiate and/or render?

**Comment by russplaysguitar** [comment]
Thanks, that should be helpful for when we finally decide to upgrade Marionette. Until then, I've applied a relatively straightforward hack to fix this bug: 

On collection `request`, unbind `view._onCollectionAdd`, then re-bind it on collection `sync`. 

Just mentioning it in case anyone else needs a quick fix.
