### ISSUE TITLE
String-encapsulated function names in events hash not invoked if events hash passed into new Marionette.View(), but is if passed into Marionette.View.extend()

### ISSUE THREAD

**Issue by komali2** [marionettejs/backbone.marionette#3628]
### Description

1. Construction of a marionette view is inconsistent across different styles. The two styles are enumerated in the JSFIDDLE (input1 is one style, input2 and input3 is the other style). 

2. Behavior should be consistent with how the `events` resolution of a stringified function works. 

### Expected behavior

I should be able to use stringified function names in the `events` hash of a view, regardless of how that view is constructed. 

See jsfiddle: https://jsfiddle.net/vx9wz7f6/2/ and open console. 

I would expect all 3 cases to work, particularly because case 3 (input3) works. 

### Actual behavior

Stringified event names don't work for `new Marionette.View({})` style constructions. 

JSFIDDLE code: 

```
const View1Class = Marionette.View.extend({
  ui: {
    input1:'#input1',
  },
  template: _.template('<input id="input1" type="checkbox">input1</input>'),
  events: {
    'input @ui.input1': 'handle_input1'
  },
  handle_input1: function(){
    console.log('input1 handled');
  }
});
const view2 = new Marionette.View({
  ui: {
    input2:'#input2',
  },
  template: _.template('<input id="input2" type="checkbox">input2</input>'),
  events: {
    'input @ui.input2': 'handle_input2'
  },
  handle_input2: function(){
    console.log('input2 handled');
  }
});
const view3 = new Marionette.View({
  ui: {
    input3:'#input3',
  },
  template: _.template('<input id="input3" type="checkbox">input3</input>'),
  events: {
    'input @ui.input3': function(){console.log('input3 handled')}
  },

})

var view1 = new View1Class();
view1.render();
view2.render();
view3.render();

$('body').append(view1.$el);
$('body').append(view2.$el);
$('body').append(view3.$el);

```

### Environment

1. Marionette version: 4.0 (provided by CDN)
2. Backbone version: 1.3.5 (provided by CDN)
3. Additional build tools, etc: None, reproducible on jsfiddle.

**Comment by paulfalgout** [comment]
I don't think this is a bug

The issue here is that `handle_input2` is not on the view.  The view options that get attached as properties to the view are listed here: https://marionettejs.com/docs/master/marionette.view.html#instantiating-a-view

So when events is passed to the base backbone view, the ui hash is normalized, but then backbone is checking if `this.handle_input2` is a function, and when it isn't it doesn't create the handler.

so the handler must be available at `view.handle_input2` during construction, prior to the initialize.

If you need to pass the handler in via an option for some reason (like you don't want to only define it on the events hash) you could do the following:
```js
const view2 = new Marionette.View({
  ui: {
    input2:'#input2',
  },
  template: _.template('<input id="input2" type="checkbox">input2</input>'),
  events: {
    'input @ui.input2': function(){ this.getOption('handle_input2').apply(this, arguments); }
  },
  handle_input2: function(){
    console.log('input2 handled');
  }
});
```
