### ISSUE TITLE
Breaking changes missing from upgrade guide 3 to 4

### ISSUE THREAD

**Issue by danspam** [marionettejs/backbone.marionette#3631]
I have found a couple of things (so far) not mentioned in the upgrade guide:

1.  filter of a CollectionView is now viewFilter and parameters have changed
2. ` { sort:false }` on a CollectionView should now be `{sortWithCollection: false}`

Also, the depreciated section of the upgrade guide in the docs is not displaying correctly.

**Comment by paulfalgout** [comment]
Yep well the entire `CollectionView` was replaced with v3.3+s `NextCollectionView` https://marionettejs.com/docs/v4.0.0/upgrade-v3-v4.html#nextcollectionview-was-renamed-to-collectionview.

That could definitely be made more clear, but for the mean time, it is mostly detailed here: https://medium.com/blog-marionettejs/next-collection-view-d335f5a9736a

As for the deprecation section.  I think that has been fixed in the repo, but not shipped to the website, or possibly the website isn't parsing the repo docs correctly :-/

**Comment by danspam** [comment]
Ah yes of course, thanks.

**Comment by mainstreetmark** [comment]
This one is causing me issues.  Marionette4 uses viewFilter, but actually renders everything somewhere in the background.  I don't want that.  If I have a large collection and only want, say, half of it, I have to go and make another, filtered collection and pass it in.  This is actually causing me WORSE performance, until i figure it out.

I miss being able to have CollectionView selectively render items.
