### ISSUE TITLE
add public api in a CollectionView for adding multiple views atonce: addChildViews

### ISSUE THREAD

**Issue by taburetkin** [marionettejs/backbone.marionette#3637]
### Description
**addChildViews()**
there is no such thing at the moment, but it can be done in next releases.
its a discussion because my vision of this api can differ from the marionette one
but i offer to discuss my thought about this

there are two question
1. passed arguments
2. implementation

but i'd like to talk in first about passed arguments

it can be done like this:
`addChildViews([view1, view2, view3, view4])`

also i think that it will be great to allow pass index with a view
and i think it can be done like this
```
addChildViews([
  [view1, options], 
  [view2, index],
  view3,
]);
```

and the second variant is spread like
`addChildViews(view1, view2, view3, view4)`
```
addChildViews(
  [view1, options], 
  [view2, index],
  view3,
);
```
it seens that there is no chance to mix this two approaches in one

1. Marionette version: 4.x
2. Backbone version: 1.3

**Comment by paulfalgout** [comment]
Duplicates https://github.com/marionettejs/backbone.marionette/issues/3593
You can add your comment about the index per view there, though I am against it.  The views should be added at an index, but not individually, preventing dealing with:
```js
addChildViews([
  [view1, index], 
  [view2, index],
  view3,
], index);
```
as well as moving targets.  The index may mean different things as the childviews are added and looped through.

In general overridden APIs should be avoided.  There are certain backbone constructs we pattern after (ie: `model.set('foo', 'bar') === model.set({ foo: 'bar' })`) but on the whole, the ideal strategy is a single API interaction unless there are functional reasons for doing so.  In this case, taking an array allows for an additional perf improvement otherwise impossible without complicating much of the internals or natural understanding of the API.  There may however be a case for using `addChildViews` as opposed to the `addChildView` variant.
