### ISSUE TITLE
Repeated sort and filter after addChildView

### ISSUE THREAD

**Issue by attenzione** [marionettejs/backbone.marionette#3667]
### Description

I've `CollectionView` with both `sort` and `filter` in realtime on the client side. Sorting and filtering are based on models attributes. Everything was perfect until I need to `addChildView`. 
In the example of `Marionette.CollectionView` in docs, `ButtonView` was added at the beginning (`index: 0`). My situation is the same - I need to add a button, which is visually pretty much the same as other child views, but without model and acts as a link. Because `ButtonView` doesn't have a model, resorting and refiltering `CollectionView` is impossible. Creating some fake model for `ButtonView` also is not a solution.
In docs, there is text: 

> **Note** Unless an index is specified, this added view will be subject to filtering and sorting and may be difficult to manage in complex situations. Use with care.

actually true for the first time, but not when sorting or filtering again.

### Expected behavior

When child view is added with `addChildView(view, index)` with explicit index, prevent this view from repeated sorting and filtering.

### Actual behavior

there is an error on repeated sort or filter because `viewComparator` or `viewFilter` are based on a model.

### Thoughts

Actually, viewFilter could be solved easily, because it has access to view and checking for the model is possible.
```
  viewFilter(view) {
    if (!view.model) { return true; }
  }
```
But no easy solution for sort.

It's better to leave current behavior, but add more options to `addChildView` - 
`preventSort` and `preventFilter` to skip child view from these functions, so this view always stays at the specified index:
```
   onRender() {
      this.addChildView(new ButtonView(), { index: 0, preventSort: true, preventFilter: true });
   }
```
Also, not related to the issue, but `index: -1` can be explicit end of the collection.

### Environment

1. Marionette version: 4.1.2
2. Backbone version: 1.4.0
3. Additional build tools, etc:
    - Webpack 4.30

**Comment by paulfalgout** [comment]
This is expected behavior.  The `addChildView` `index` allows for adding a view without dealing with sort or filter, but it cannot account for a continued index after the fact, that would make sorting and filtering near impossible to manage or understand.  The `viewComparator` also has access to the view, so it can follow the same pattern you laid out in the `viewFilter`  If you do not want to customized the `viewFilter` or `viewComparator` to account for the customly added view, then it is best (add perhaps easier anyhow) to `detachChildView` it from the collection in something like `before:sort` and re-`addChildView` afterwards.

**Comment by attenzione** [comment]
> it is best (add perhaps easier anyhow) to `detachChildView` it from the collection in something like `before:sort` and re-`addChildView` afterwards.

This is how I finally solved this.

But I like the idea to have `preventSort` and `preventFilter` for child view. What do you think, is it possible to implement? 

I understand that insert custom view somewhere in the middle of the collection and deal with sort or filter is unpredictable, but this could be developer decision.
If I add child view at the beginning or end (`{index: -1}`) than `CollectionView` could manage custom views and prepend or append them after sort or filter.

**Comment by paulfalgout** [comment]
I think the implementation would be complex, costly, and carry plenty of caveats regarding how sorting and filtering would work.  It would seem quite odd to only support it at the beginning or end `({ index: null })`, and supporting it elsewhere would be far from easy, when `detachChildView` is relatively straight-forward

**Comment by attenzione** [comment]
`detachChildView` is not intuitive and not even solution, just workaround (agh yeah, works), but `addChildView` with such implementation is suitable for a narrow number of tasks.

**Comment by taburetkin** [comment]
@paulfalgout we already discuss this, i am not alone :)
@attenzione collection view sorts and filters all the views and each view may have a model, but not necessary
so, in case you are dealing with some complex collection view you have collection model views which you are expect to be sorted with viewFilter and few custom views which should not be filtered with view filter
in this case you can add hook on `addChild` and mark your custom views and create a view filter with respect to this flag custom/model view.

**Comment by attenzione** [comment]
@taburetkin you're right, I'm having the complex view with the complex (mixed) collection and I understand everything above about viewFilter and viewComparator, but from my point of view (as the developer) this is unnecessary code complication. 
@paulfalgout mentioned, that this is expected behavior. For me, when I `addChildView` manually (this is important) I do not expect such behavior. 
I just suggesting to extend functionality without losing any compatibility.

**Comment by taburetkin** [comment]
here is an example how it can be solved:
https://codepen.io/dimatabu/pen/oRNYqp?editors=0010

keep in mind that viewFilter and viewComparator does not aware of collection or models.
this methods works only with rendered views, no matter if them are customs or not.

**Comment by paulfalgout** [comment]
I think `this.addChildView(new ButtonView(), { index: 0, preventSort: true });` is an interesting API, but nearly impossible to really understand or implement.
for instance what does this do:
```
const testView = this.addChildView(new ButtonView(), { index: 4, preventSort: true });
this.addChildView(new ButtonView(), { index: 3 });
this.addChildView(new ButtonView(), { index: 4 });
this.addChildView(new ButtonView(), { index: 4, preventSort: true });
this.sort();
this.findIndexByView(testView); // what's this?
```
Not only that but it seems to me to determine if these flags are in use, Mn would have to loop through all of the children once, _prior_ to actually sorting using the user's custom defined comparator, because you can't do this action within the sort (since the comparator can be customized)
And even then, under-the-hood it seems to me the _best_ possible behavior is that it detaches and then _somehow_ reattached (to where I have no idea.. I suppose we have to record the added indexes somehow and play them back??)

Sooo we'd be adding significant cost to the potential for someone to use this flag, and even more significant cost if it's actually used, when manually detaching/attaching or making a custom comparator with the current API is much less costly.

If you have an idea for a solution, share it, but right now, this API seems impractical.  I cannot even begin to plan out how this would work.

**Comment by paulfalgout** [comment]
This issue seems stale to me.  If there's anything new, we can reopen
