### ISSUE TITLE
Add template option to CollectionView

### ISSUE THREAD

**Issue by aaronchi** [marionettejs/backbone.marionette#458]
Is there a reason not to give CollectionView the ability to render a template? I've been using CompositeView but it seems unnecessary because I don't actually have a parent model to render.

The use case is a collection with a wrapper that includes items like a toolbar. Ideally, I'd like to put all of the logic related to the toolbar functionality into the collectionView, but I'm forced to use a compositeView with a dummy parent model because collectionView doesn't support a rendering template.

**Comment by jonas-db** [comment]
Since the CompositeView is deprecated, how can we display a collectionview with a custom template? I remember that there was a childViewContainer option, but i do not find it anymore?

**Comment by paulfalgout** [comment]
In v3 you use a region in a view and `replaceElement` during the `show` so that there is no wrapping element which duplicates the functionality of `CompositeView` and its `childViewContainer`.  This is documented here: https://github.com/marionettejs/backbone.marionette/blob/v3.0.0-pre.5/docs/marionette.collectionview.md#tables-using-marionette-3
